### ISSUE TITLE
Code folding support in the language server

### ISSUE THREAD

**Issue by SquidDev** [leanprover/lean4#1012]
Several language constructs in Lean are often written without indentation, for instance `section`, `namespace`, `inductive` and `match`:

```lean
section sect

inductive Maybe (α : Type) : Type 
| none
| some (val : α)

example : Maybe α → α → α := λ m default =>
  match m with
  | Maybe.some x => x
  | Maybe.none => default

end sect
```

Sometimes it may be useful to fold these away (especially in the case of section/namespace). However editors often use indentation as a guide for foldable regions, and so these constructs are not considered foldable.

[LSP has support for custom folding ranges](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_foldingRange), which allows the language server to define its own regions. I've had a quick flick through `RequestHandling.lean`, and it definitely seems like it would be possible to implement for the basic cases above.

It's worth noting that folding range requires you to provide _all_ ranges (including those previously inferred via indentation), and I'm not sure how well this'd work with the rest of Lean's extensible syntax.

I'd be happy to help with/work on the implementation if useful, just felt it was worth getting some feedback/thoughts first!

**Comment by Kha** [comment]
Feel free to give it a try if you want, you already found the right place to start, after all. You can always ask for help on Zulip if you're stuck.

For a first implementation, I would focus on folding namespaces, sections, and individual commands. The merit of term-level folds is not clear to me, especially since terms may not necessarily start at the beginning of the line. Imports and (doc) comments are another possible use case suggested by the spec.
