### ISSUE TITLE
`cases` and `Meta.cases` fail for targets containing metavariables

### ISSUE THREAD

**Issue by JLimperg** [leanprover/lean4#1073]
Sort of minimal working example:

```lean
import Lean

inductive Com where
| Seq : Com → Com → Com

open Com

inductive BigStep : Com → Unit → Unit → Prop where
| Seq (h1 : BigStep c1 s1 s2) (h2 : BigStep c2 s2 s3) : BigStep (Seq c₁ c₂) s1 s3

-- `cases h` with no metavariables in the goal succeeds.
example (h : BigStep (Seq (Seq c₁ c₂) c₃) s₁ s₂) : BigStep (Seq c₁ (Seq c₂ c₃)) s₂ s₂ := by
  cases h
  case _ h1 h2 =>
    apply BigStep.Seq
    case h1 => exact h1
    case h2 => exact h2

-- `cases h` with metavariables in the goal produces a weird goal.
example (h : BigStep (Seq (Seq c₁ c₂) c₃) s₁ s₂) : BigStep (Seq c₁ (Seq c₂ c₃)) s₂ s₂ := by
  apply BigStep.Seq
  case h1 =>
    cases h
    /-
    c₁ c₂ c₃ : Com
    s₁ s₂ : Unit
    c1 : Com
    s2 : Unit
    c2 : Com
    h1 : BigStep c1 s₁ s2
    h2 : BigStep c2 s2 s₂
    ⊢ BigStep (?m.4066 (_ : BigStep (Com.Seq (Com.Seq c₁ c₂) c₃) s₁ s₂)) s₂
        (?m.4067 (_ : BigStep (Com.Seq (Com.Seq c₁ c₂) c₃) s₁ s₂))
    -/
    assumption -- fails
  case h2 =>
    sorry

-- `Meta.cases h` has the same issue.

open Lean.Meta in
open Lean.Elab.Tactic in
elab &"meta_cases" h:ident : tactic =>
  liftMetaTactic λ goal => do
    let fvar := (← getLocalDeclFromUserName h.getId).fvarId
    return (← Lean.Meta.cases goal fvar).map (·.mvarId) |>.toList

example (h : BigStep (Seq (Seq c₁ c₂) c₃) s₁ s₂) : BigStep (Seq c₁ (Seq c₂ c₃)) s₂ s₂ := by
  apply BigStep.Seq
  case h1 =>
    meta_cases h
    /-
    c₁ c₂ c₃ : Com
    s₁ s₂ a : Unit
    c1 : Com
    s1 s2 : Unit
    c2 : Com
    h1 : BigStep c1 s1 s2
    h2 : BigStep c2 s2 s₁
    ⊢ BigStep (?m.5364 (_ : BigStep (Com.Seq (Com.Seq c₁ c₂) c₃) s1 s₁)) s₂
        (?m.5365 (_ : BigStep (Com.Seq (Com.Seq c₁ c₂) c₃) s1 s₁))
    -/
    assumption -- fails
  case h2 =>
    sorry
```

Tested on nightly-2022-03-25.

**Comment by leodemoura** [comment]
Both `cases` and `Meta.cases` use the `Meta.unifyEqs` to perform dependent elimination.
After `apply BigStep.Seq`, the target in the main goal is `BigStep ?c1 s₂ ?s2`, and `h` is in the local context for `?c1` and `?s2`. That is, Lean can assign terms containing `h` to these two metavariables.
Then, during `Meta.unifyEqs`, we reach the state
```lean
...
⊢ h = BigStep.Seq h1✝ h2✝ → BigStep ?c1 s₂ ?s2
```
before substituting `h` with `BigStep.Seq h1✝ h2✝`. We haven't assigned values to `?c1` and `?s2` yet, but when we do Lean wants to record that the `h` there must be replaced with `BigStep.Seq h1✝ h2✝`. Thus, it creates two auxiliary metavariables to "track" this dependency, and produces the state.
```lean
...
⊢ BigStep (?m.3212 (BigStep.Seq h1✝ h2✝)) s₂ (?m.3213 (BigStep.Seq h1✝ h2✝))
```
Note that even if it hadn't done this bookkeeping, the `assumption` tactic would still fail since there is no assumption where the second argument is `s₂`.

**Comment by JLimperg** [comment]
Thank you for the detailed explanation. I actually made not one but several typos in the original example, so it wasn't very realistic. Here's a fixed version, which still exhibits the same behaviour:

```lean
inductive Com where
| Seq : Com → Com → Com

open Com

inductive BigStep : Com → Unit → Unit → Prop where
| Seq (h₁ : BigStep c₁ s₁ s₂) (h₂ : BigStep c₂ s₂ s₃) : BigStep (Seq c₁ c₂) s₁ s₃

example (h : BigStep (Seq (Seq c₁ c₂) c₃) s₁ s₂) :
    BigStep (Seq c₁ (Seq c₂ c₃)) s₁ s₂ := by
  apply BigStep.Seq
  case h₁ =>
    cases h with
    | Seq h₁ h₃ =>
      cases h₁ with
      | Seq h₁ h₂ =>
        /-
        case Seq.Seq
        c₁ c₂ c₃ : Com
        s₁ s₂ s₂¹ : Unit
        h₃ : BigStep c₃ s₂¹ s₂
        s₂ : Unit
        h₁ : BigStep c₁ s₁ s₂
        h₂ : BigStep c₂ s₂ s₂¹
        ⊢ BigStep c₁ s₁ (?m.2053 (_ : BigStep (Com.Seq (Com.Seq c₁ c₂) c₃) s₁ s₂))
        -/
        apply h₁
  case h₂ =>
    sorry
```

Now, this proof attempt is doomed to fail, so in this sense Lean is correct: `h₁` cannot be applied here because `s₂` is not in the lctx of `?m.2053`. However, Lean's response still seems fishy:

- `?m.2053` is not registered as a goal. (I thought that tactics always return unsolved metas as goals; is this an invariant you generally enforce?)
- The equation `h = BigStep.Seq h1✝ h2✝` is irrelevant since `BigStep` is a `Prop`, so maybe Lean does not need to record the fact that `?m.2053` can refer to `h`.
- `apply h₁` fails with a somewhat uninformative error message:
  ```text
  tactic 'apply' failed, failed to unify
    BigStep c₁ s₁ s₂
  with
    BigStep c₁ s₁ (?m.2053 (_ : BigStep (Com.Seq (Com.Seq c₁ c₂) c₃) s₁ s₂))
  ```
  Ideally it would point out that `s₂` cannot be assigned to `?m.2053` since it's not in scope.

For comparison, here's how Coq handles the situation:

```coq
Inductive Com : Type :=
| Seq : Com -> Com -> Com.

Inductive BigStep : Com -> True -> True -> Prop :=
| BigStep_Seq {c1 c2 s1 s2 s3} :
  BigStep c1 s1 s2 ->
  BigStep c2 s2 s3 ->
  BigStep (Seq c1 c2) s1 s3.

Example ex1 {c1 c2 c3 s1 s2} (h : BigStep (Seq (Seq c1 c2) c3) s1 s2) :
  BigStep (Seq c1 (Seq c2 c3)) s1 s2.
Proof.
  eapply BigStep_Seq.
  - inversion_clear h as [c1' c2' s1' s2' s3 h1 h2].
    inversion_clear h1 as [c1'' c2'' s1'' s2'' s3 h3 h4].
    (*
    c1, c2, c3 : Com
    s1, s2, s2' : True
    h2 : BigStep c3 s2' s2
    s2'' : True
    h3 : BigStep c1 s1 s2''
    h4 : BigStep c2 s2'' s2'
    ============================
    BigStep c1 s1 ?s2
    *)
    Fail apply h3.
    (*
    The command has indeed failed with message:
    In environment
    c1, c2, c3 : Com
    s1, s2, s2' : True
    h2 : BigStep c3 s2' s2
    s2'' : True
    h3 : BigStep c1 s1 s2''
    h4 : BigStep c2 s2'' s2'
    Unable to unify "?s2" with "s2''" (cannot instantiate "?s2" because "s2''" is not in its scope: available arguments
    are "c1" "c2" "c3" "s1" "s2").
    *)
    admit.
  - admit.
Abort.
```

**Comment by leodemoura** [comment]
> ?m.2053 is not registered as a goal. (I thought that tactics always return unsolved metas as goals; is this an invariant you generally enforce?)

No, this is not the case in general. This is an auxiliary metavariable for making sure the resulting term is well-formed. Note that we also have "delayed assignment"s for them. 

> The equation h = BigStep.Seq h1✝ h2✝ is irrelevant since BigStep is a Prop, so maybe Lean does not need to record the fact that ?m.2053 can refer to h.

Note that the recording is needed to make sure we have a well-formed term in the end. 
The goal before the `cases` contains metavariables. We can assign terms containing `h` to these metavariables much later. When we do that, this recording step tells us to replace `h` with `BigStep.Seq h1✝ h2✝`. We cannot leave `h` there. Otherwise, we will get the "unexpected free variable" when we sent the term to the Kernel.

> apply h₁ fails with a somewhat uninformative error message:

Yes, error messages can be improved, but I think this is a different issue.
In general, we cannot pinpoint a single reason for a unification failure. 
Our goal is to have browseable/searchable traces in Lean, and the information you suggested will be there in the trace.

**Comment by JLimperg** [comment]
> No, this is not the case in general. This is an auxiliary metavariable for making sure the resulting term is well-formed. Note that we also have "delayed assignment"s for them.

Ah, this is very good to know. Then I have some code to update...

> Note that the recording is needed to make sure we have a well-formed term in the end.

I see, that explains it. Thanks again! I wonder how Coq does it then -- maybe they carry around a substitution with each mvar.

> Yes, error messages can be improved, but I think this is a different issue.

Fair, this is hopefully not a situation people will run into often.
