### ISSUE TITLE
Universe polymorphic return type causes for in increment to fail

### ISSUE THREAD

**Issue by ammkrn** [leanprover/lean4#1136]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Returning an element of a universe-polymorphic type from a `for in` loop seems to cause issues if the loop also has a mutable local variable. This appears to persist if the local isn't in the return type (see the third example).

### Steps to Reproduce

These are the two cases that cause issues:
```
/-
`B` is in `Type v`, and we have a mutable local which is in the return type:

stuck at solving universe constraint
  v =?= max v ?u.1291
while trying to unify
  (?m.1299 × ?m.1571) ?m.1299 ?m.1571
with
  (?m.1299 × ?m.1571) ?m.1299 ?m.1571

application type mismatch
  { fst := none, snd := idx }
argument
  idx
has type
  Nat : Type
but is expected to have type
  ?m.1669 node k : Type v
-/
def minimalBad {A : Type} {B : Type v} [Ord A] [Inhabited B] (node : Array A) (k : A) : (B × Nat) := Id.run <| do
  let mut idx : Nat := 0
  for k' in node do
    match Ord.compare k k' with
    | Ordering.gt => idx := idx + 1; continue
    | Ordering.lt => continue
    | Ordering.eq => return (Inhabited.default, idx)
  (Inhabited.default, idx)

/-
Leave `B` in `Type v`, but don't try to return the local variable:

typeclass instance problem is stuck, it is often due to metavariables
  Add (?m.1772 node k)
-/
def minimalBadDontReturnIncrement {A : Type} {B : Type v} [Ord A] [Inhabited B] (node : Array A) (k : A) : B := Id.run <| do
  let mut idx : Nat := 0
  for k' in node do
    match Ord.compare k k' with
    | Ordering.gt => idx := idx + 1; continue
    | Ordering.lt => continue
    | Ordering.eq => return Inhabited.default
  Inhabited.default
```

These two cases work fine, so it seems to be just the combination of local and universe polymorphism:
```
/- Works if `B` is in `Type v`, but we get rid of the local variable -/
def minimalOkPoly {A : Type} {B : Type v} [Ord A] [Inhabited B] (node : Array A) (k : A) : B := Id.run <| do
  for k' in node do
    match Ord.compare k k' with
    | Ordering.gt => continue
    | Ordering.lt => continue
    | Ordering.eq => return (Inhabited.default)
  (Inhabited.default)

/- Works with the local if we demote `B` to `Type` -/
def minimalOkLocal {A : Type} {B : Type} [Ord A] [Inhabited B] (node : Array A) (k : A) : (B × Nat) := Id.run <| do
  let mut idx : Nat := 0
  for k' in node do
    match Ord.compare k k' with
    | Ordering.gt => idx := idx + 1; continue
    | Ordering.lt => continue
    | Ordering.eq => return (Inhabited.default, idx)
  (Inhabited.default, idx)
```
**Expected behavior:** 

If there's a reason why this shouldn't work, I guess just a better error message would be appropriate.

### Versions

leanprover/lean4:nightly-2022-04-29
vscode extension v0.16.46

**Comment by leodemoura** [comment]
This is a limitation of the `do` notation. It is using the `bind` which has type:
```lean
@bind : {m : Type u_1 → Type u_2} → [self : Bind m] → {α β : Type u_1} → m α → (α → m β) → m β
```
Note that `α` and `β` must be in the same universe since they are both used as arguments to `m`. The side-effect is that the values manipulated by a `do` block must all be in the same universe. We can use the universe lift `ULift` to work around this limitation, but they are very inconvenient to use. Here is how to write your examples using `ULift`
```
def Nat' : Type v := ULift Nat -- a universe polymorphic `Nat`

instance : OfNat Nat' n where
  ofNat := ULift.up n

instance : Add Nat' where
  add a b := ULift.up (a.down + b.down)

def minimalBad {A : Type v} {B : Type v} [Ord A] [Inhabited B] (node : Array A) (k : A) : B × Nat' := Id.run <| do
  let mut idx : Nat' := 0
  for k' in node do
    match Ord.compare k k' with
    | Ordering.gt => idx := idx + 1; continue
    | Ordering.lt => continue
    | Ordering.eq => return (default (α := B), idx) -- See remark below [*]
  (default, idx)

def minimalBadDontReturnIncrement {A : Type v} {B : Type v} [Ord A] [Inhabited B] (node : Array A) (k : A) : B := Id.run <| do
  let mut idx : Nat' := 0
  for k' in node do
    match Ord.compare k k' with
    | Ordering.gt => idx := idx + 1; continue
    | Ordering.lt => continue
    | Ordering.eq => return Inhabited.default
  Inhabited.default
```
The example above may not look too bad, but the error messages are horrible until we get it right. We should invest time in improving the error messages in the future, but this is not a high priority right now since we feel like we can move forward without having to write universe polymorphic monadic code

Regarding [*]: Note that I had to provide the value of an implicit argument at `default (α := B)`. This is a workaround for a "stuck at universe constraint" error message. It happens because the `do` elaborator is not propagating the expected type for the whole `do` block as well as it could. This can be improved in the near future.

**Comment by ammkrn** [comment]
Thanks for taking the time to explain, I appreciate the examples. I'll close this issue since it seems to be on your radar but isn't pressing.
