### ISSUE TITLE
Anomalous parsing of structure expressions

### ISSUE THREAD

**Issue by paulch42** [leanprover/lean4#1218]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Per section 9.3 of the Manual, the following is allowed:
```
structure Point where
 x : Nat
 y : Nat
deriving Repr

def mkPoint (a : Nat) : Point where
  x := 1
  y := a
```
However, the following is also valid:
```
def mkPoint1 (a : Nat) : Point where
  x := 1y := a

#eval mkPoint1 2 -- { x := 1, y := 2 }
```
Note that `x := 1 y := a` and `x := ay := a` in the body of `mkPoint1` throw errors as expected.
### Steps to Reproduce

1. Copy the above code into VS Code.

**Expected behavior:** 
Syntax error

**Actual behavior:**
Parsing is successful

**Reproduces how often:**
100%

### Versions

leanprover/lean4:nightly-2022-06-13

### Additional Information

None

**Comment by leodemoura** [comment]
I can see this is confusing.
`1y` is being parsed as the literal `1` followed by the identifier `y`. I never noticed this problem before, but it seems to be in every Lean version. In Lean 3, the following is accepted.
```lean
def f (x y : nat) := x + y

def a := 1

#eval f 1a  -- 2
``` 
In Lean 4, this example is not accepted because we force function application arguments to be preceded by whitespace to disambiguate between `f a[1]` (i.e., `f (a[1])`) and `f a [1]` (i.e., `f (a) ([1])`).
It will be great to hear what others think about this issue cc @Kha @gebner @digama0 @Vtec234 @EdAyers 
BTW, we can create variants of this issue with character and string literals. The one with character literals also looks weird. 
```lean
structure Point where
 x : Char
 y : Nat

def mkPoint (a : Nat) : Point where
  x := 'a'y := a
```

**Comment by gebner** [comment]
> BTW, we can create variants of this issue with character and string literals. The one with character literals also looks weird.

You can also do this with `()`, `(1,2)`, `⟨1,2⟩`, `{fst := 1, snd := 2}` instead of literals.  Another option is to write `x := (a)y:= a`  The possibilities seem to be endless.

What I find counterintuitive here is that we accept the "multi-line" syntax even if it's on a single line.

**Comment by gebner** [comment]
This is another headscratcher:
```lean
def mkPoint?? (x y : Nat) : Point :=
  { x y }
```

**Comment by leodemoura** [comment]
@gebner 

> You can also do this with (), (1,2), ⟨1,2⟩, {fst := 1, snd := 2} instead of literals. Another option is to write x := (a)y:= a The possibilities seem to be endless.

I can see this one is not ideal, but it is not as bad as `x := 1y := a`.

> What I find counterintuitive here is that we accept the "multi-line" syntax (with newlines instead of semicolons) even if it's on a single line.

Yeah, it may look weird, but it is the expected behavior of the idiom using the combinators `withPosition` + optional `,`/`;`.
One way to make it more intuitive is to have an `optionalOrLineBreak p` combinator that expects a line break in the trail if the parse `p` fails. Too hackish?

**Comment by leodemoura** [comment]
> This is another headscratcher:
> 
> ```lean
> def mkPoint?? (x y : Nat) : Point :=
>   { x y }
> ```

Yeah, this one also looks really bad.

**Comment by leodemoura** [comment]
I tried the `optionalOrLinebreak`, it helps at
```lean
def optSemicolon (p : Parser) : Parser := ppDedent $ optionalOrLinebreak ";" >> ppLine >> p
```
This is good because `optSemicolon` is used in so many places, and it fixes other instances of the issue such as
```lean
def f (y : Nat) :=
  let x := 1x + y -- Error
```
However, `optionalOrLinebreak` does not help in cases where we allow a trailing `,` such as `{x y}`. If we blindly use `optionalOrLineBreak` in this parser, we would have to write `{x, y, }` or 
```lean
{x, y
}
```

**Comment by leodemoura** [comment]
@gebner The commit above is in a separate branch, it fixes the original issue reported here, but not
```lean
def mkPoint?? (x y : Nat) : Point :=
  { x y }
```
Note that I had to fix a test because of the trailing issue in a test using the `where` notation in a quotation.  We had a `)` instead of a line break.

**Comment by Kha** [comment]
@gebner I was working in a very similar direction, just without new primitive parsers (but we can always add new primitive pretty printer hint parsers, of course): https://github.com/Kha/lean4/commit/29f993ed2d27a33e9c89141db9d3057b060985fd
Tests are not passing yet since it's quite laborious to find all the place where the affected syntax is destructured manually.
