### ISSUE TITLE
Can't substantiate WF recursion when doing `cases` on a type parameter

### ISSUE THREAD

**Issue by fpfu** [leanprover/lean4#1228]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Steps to Reproduce

```lean
inductive Foo (n : Nat) : Type
| foo (t: Foo n): Foo n

namespace Foo
  inductive Bar: Foo n → Prop 

  theorem ex₁ {s: Foo n} (H: s.Bar): True := by
    cases s
    case foo s' =>
      cases n; sorry
      have: Bar s' := sorry
      exact ex₁ this
  termination_by _ => sizeOf s

  theorem ex₂
    {s: Foo n}
    (H: s.Bar):
    True := by
    generalize hs': s = s'
    match s' with 
    | foo s' =>
      have: Bar s' := sorry
      have hterm: sizeOf s' < sizeOf s := by simp_all_arith
      exact ex₂ this
  termination_by _ => sizeOf s

  theorem ex₃ {s: Foo n} (H: s.Bar): True := by
    cases s
    case foo s' =>
      match n with
      | 0 => sorry
      | _ => 
        have: Bar s' := sorry
        exact ex₃ this
  termination_by _ => sizeOf s

  -- it works
  theorem ex₄ {s: Foo n} (H: s.Bar): True := by
    match s with
    | foo s' =>
    match n with
    | 0 => sorry
    | _ => 
      have: Bar s' := sorry
      exact ex₄ this
  termination_by _ => sizeOf s
    
```

**Expected behavior:** examples should work

**Actual behavior:** get error messages

`ex₁`:
```
failed to prove termination, possible solutions:
  - Use `have`-expressions to prove the remaining goals
  - Use `termination_by` to specify a different well-founded relation
  - Use `decreasing_by` to specify your own tactic for discharging this kind of goal
n : Nat
s✝ : (s : Foo n) ×' Bar s
: ∀ (y : (n : Nat) ×' (s : Foo n) ×' Bar s),
  (invImage (fun a => PSigma.casesOn a fun n snd => PSigma.casesOn snd fun s snd => sizeOf s) instWellFoundedRelation).1
      y { fst := n, snd := s✝ } →
    True
s : Foo n
H✝¹ : Bar s
a✝ :
  ∀ (y : (n : Nat) ×' (s : Foo n) ×' Bar s),
    (invImage (fun a => PSigma.casesOn a fun n snd => PSigma.casesOn snd fun s snd => sizeOf s)
            instWellFoundedRelation).1
        y { fst := n, snd := { fst := s, snd := H✝¹ } } →
      True
t✝ : Foo n
: s = foo t✝
: Bar (foo t✝)
n✝ : Nat
: n = Nat.succ n✝
s' : Foo (Nat.succ n✝)
H : Bar (foo s')
this : Bar s'
⊢ sizeOf s' < sizeOf s
```

`ex₂` and `ex₃`:

```
failed to add functional argument to 'matcher' application
  failed to add argument to matcher application, type error when constructing the new motive
```

**Reproduces how often:** 100%

### Versions

`nightly-2022-06-17`

**Comment by leodemoura** [comment]
Lean will first elaborate the recursive definition, and then try using `WellFounded.fix` to justify the termination. Consider the simple example:
```lean
  def f (x : Nat) : Nat :=
    match x with
    | 0 => 1
    | z+1 => 2*f z
  termination_by _ x => x
```
It is compiled to something equivalent to
```lean
def f :=
  WellFounded.fix wfr (fun (x : Nat) (F : (y : Nat) -> y < x -> Nat) => <f-body>) 
```
We replace recursive occurrences with `F`-applications. Whenever we perform case analysis on `x`, we also update `F`s type since it depends on `x`. In the example above, the type of `F` becomes `(F : (y : Nat) -> y < z+1 -> Nat) => <f-body>)` in the `z+1` case. This is why we succeed in using `F` to replace the recursive application `f z`. 
In the initial design, we only considered case analysis performed using `match`-applications. Later, we added support for `casesOn` applications produced by the `cases` tactic. In both cases, Lean has to compute a new "motive" and may fail to produce a type correct one.
I don't see how to make it 100% bullet-proof. We have a similar issue with the `rewrite` tactic, where it fails because the computed motive is not type-correct. 
That being said, you can help Lean by using the `h :` modifier in the `cases` tactic. Example:
```lean
  theorem ex₁ {s: Foo n} (H: s.Bar) : True := by
    cases h₁ : s
    case foo s' =>
      have: Bar s' := sorry
      cases h₂ : n; sorry
      exact ex₁ this
  termination_by _ => sizeOf s
```
Then, we will have the equalities `h₁ : s = foo s'` and `h₂ : n = n✝` in the local context, and even if Lean fails to refine the motives, it can use these equalities to finish the termination proof.

**Comment by leodemoura** [comment]
The commit above makes sure `WF/Fix.lean` does not fail completely when it cannot refine the type of `F` in a `match`-application because the new motive is not type-correct. This is needed to address the error at `ex₂`.
With this notification, all your examples can be processed if we add the `h :` annotations to `cases`.
Therefore, I am closing this issue. Feel free to reopen it if the solution is not satisfactory.
