### ISSUE TITLE
`simp` structure projection unification problem

### ISSUE THREAD

**Issue by fpfu** [leanprover/lean4#1253]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Steps to Reproduce

```lean
inductive Foo (f: Fin n): Nat → Prop
| mk: Foo f f.val
theorem foo {f: Fin n}: Foo f f.val := .mk
example (hf: f < n): Foo ⟨f, hf⟩ f := by simp only[foo]
```

**Expected behavior:** example probably should work because the corresponding Lean3 code works:

```lean
structure fin' (n: ℕ) :=
  (val: ℕ) 
  (isLt: val < n)

inductive Foo {n} (f: fin' n): ℕ → Prop
| mk: Foo f.val
theorem foo {n} {f: fin' n}: Foo f f.val := Foo.mk
example {f n} (hf: f < n): Foo ⟨f, hf⟩ f := by simp only[foo]
```

**Actual behavior:** get unsolved goals message:

```
unsolved goals
f n : Nat
hf : f < n
⊢ Foo { val := f, isLt := hf } f
```

**Reproduces how often:** 100%

### Versions

`nightly-2022-06-26`

### Additional information

Not sure if this problem can be fixed or if it is a limitation of a discrimination tree usage, but it implies that every `simp` lemma involving some structure and its projection must be repeated for all examples to work:

```lean
inductive Foo (f: Fin n): Nat → Prop
| mk: Foo f f.val
@[simp] theorem foo   {f: Fin n}: Foo  f     f.val := .mk
@[simp] theorem foo' {hf: f < n}: Foo ⟨f, hf⟩ f     := .mk
example  (f: Fin n): Foo  f     f.val  := by simp only[foo]
example  (f: Fin n): Foo  f     f.val  := by simp only[foo'] -- fails
example (hf: f < n): Foo ⟨f, hf⟩ f      := by simp only[foo]  -- fails
example (hf: f < n): Foo ⟨f, hf⟩ f      := by simp only[foo']
```

### UPD: another failing example
```lean
opaque bar: Fin n → Prop
example (h: bar f): bar ⟨f.val, f.isLt⟩ := by simp only [h]
```
however, it also doesn't work in Lean 3:
```lean
structure fin' (n: ℕ) :=
  (val: ℕ) 
  (isLt: val < n)

constant bar: ∀{n}, fin' n → Prop
example {n} {f: fin' n} (h: bar f): bar ⟨f.val, f.isLt⟩ := by simp only [h]
```

**Comment by leodemoura** [comment]
The behavior above is expected. As you pointed out it is due to the use of discrimination trees to index `simp` theorems. Before adding a pattern to the discrimination tree, we unfold `[reducible]` symbols. So, theorem `foo` is only applied if the target term matches the pattern `@Foo * * (Foo.0 *)`, where `*` are wildcards, and `Foo.0` is `Foo`'s first projection. 
We can use the annotation `no_index` to instruct Lean to treat a subterm as a wildcard. For example, we can write the code above as:
```lean
inductive Foo (f: Fin n): Nat → Prop
| mk: Foo f f.val
theorem foo {f: Fin n}: Foo f (no_index f.val) := .mk
example (hf: f < n): Foo ⟨f, hf⟩ f := by simp only[foo] -- works
```
The Lean 3 version works without any annotation because Lean 3 uses a very primitive indexing data-structure which causes scalability issues. 
I am adding a new test with the `no_index` annotation and will close this issue since the behavior is expected.
