### ISSUE TITLE
erroneous 'redundant alternative'

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#1411]
```lean
namespace Lean
syntax "foo " binderIdent : term
example : Syntax → MacroM Syntax 
  | `(foo _) => `(_)
  | `(foo $x:ident) => `($x:ident) -- redundant alternative
  | _ => `(_)
```

I would also suggest making this check optional / a warning, because it doesn't impede either code generation or correctness.

**Comment by digama0** [comment]
Actually the error message is not erroneous, but rather the pattern `` `(foo _)`` is matching `foo` followed by anything, rather than the previous behavior of matching `foo` followed by a literal `_`. We already have the syntax `` `(foo $_)`` for matching `foo` followed by anything, but now we can't match just `foo _` anymore, so I would consider this a bug.

**Comment by leodemoura** [comment]
@Kha This is the `<|>` issue again. We have
```lean
def binderIdent : Parser  := ident <|> hole
```

**Comment by gebner** [comment]
It has nothing to do with `<|>` or any new behavior of `_`. The issue here is that `_` is an atom and therefore matches everything.

The obvious fix here is to standardize on `syntax binderIdent := ident <|> hole` with `syntax hole := "_" ` so that the underscore gets its own node.  See also #1275 and https://github.com/leanprover-community/mathport/pull/152#issuecomment-1173841553

**Comment by digama0** [comment]
A big +1 from me on making the grammar more regular and having only one way to write `ident <|> "_"`
