### ISSUE TITLE
Hover doc strings 

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#1443]
In the current implementation, elab doc string is taken by preference to the syntax doc string. For example, when users hover over the `calc` keyword, they get the doc string.
```
Elaborator for the `calc` term mode variant.
``` 
instead of the (much more detailed) syntax doc string
``````
Step-wise reasoning over transitive relations.
```
calc
  a = b := pab
  b = c := pbc
  ...
  y = z := pyz
```
proves `a = z` from the given step-wise proofs. `=` can be replaced with any
relation implementing the typeclass `Trans`. Instead of repeating the right-
hand sides, subsequent left-hand sides can be replaced with `_`.

`calc` has term mode and tactic mode variants. This is the term mode variant.

See [Theorem Proving in Lean 4][tpil4] for more information.

[tpil4]: https://leanprover.github.io/theorem_proving_in_lean4/quantifiers_and_equality.html#calculational-proofs
``````
 At #1403, @kha reported that this is the intended behavior since a single syntax can have multiple elaborators, so the elaborator docstring is expected to be the more specific one we should show and jump to first.
@digama0 points out that 

> From a doc writer's perspective, it is a lot harder to write good elab comments than syntax comments, because when you are documenting a tactic like simp you really want all the syntactic variants to be documented there, not spread over multiple comments where the user never gets the full picture.

Thread #1403 also suggests that there are two kinds of consumers for these doc strings: users and code-readers.

**Comment by leodemoura** [comment]
I am marking this issue as an RFC to get feedback from the community.

**Comment by gebner** [comment]
> to be the more specific one we should show and jump to first.

Just to be clear: those are two completely different issues.  You can jump to either the elaborator or the syntax definition from the editor depending on which command you use.  So this is no argument for which docstring to show in the hover.

My current feeling is that we should show (only) the syntax docstring.  In virtually all cases right now, the elaborator/expander is just an implementation detail.  There might also be multiple elaborators/expanders, multiplying the documentation effort.  This might change if we add some more "extensible" syntax (similar to how we might want to show docstrings for type class instances in addition to or instead of the type class operation docstrings):
```lean
syntax "frobnicate!" term : term

-- and in another module:
/-- The MyStuff frobnication frobnicates my stuff. -/
macro_rules
  | `(frobnicate! MyStuff + 2) => ...
```
