### ISSUE TITLE
Precompilation breakage on Windows

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#1758]
See https://github.com/JLimperg/aesop/issues/28
May or may not have something to do with this line :thinking: 
https://github.com/leanprover/lean4/blob/9fd433785b35a4a309022db05ec6074da64da209/src/library/compiler/ir_interpreter.cpp#L300

**Comment by Kha** [comment]
That function actually does an out-of-bounds read if we ever do load more than 128 modules, so either we got "lucky" or this is not the (sole) issue.

**Comment by tydeu** [comment]
To copy over here a note form me on https://github.com/JLimperg/aesop/issues/28: The problem also occurs in Alloy which has far less than 128 precompiled modules, so the bug is probably not just that. The bug is also localized in the `registerPersistentEnvExtension`, specifically in that `persistentEnvExtensionsRef` will already have a functioning extension registered if the module is precompiled and imported. 

The problem is also likely not that the intiialize block is being run twice as that would likely cause other problems that I have not experienced in Alloy.

**Comment by Kha** [comment]
The initializer is being run twice. 
![image](https://user-images.githubusercontent.com/109126/202417276-c2680c71-0014-4798-b418-5fdd2ade356f.png)

**Comment by Kha** [comment]
I cannot reproduce the Aesop issue on the most recent commit (nightly 11-14). It would be great to have a self-contained reproducer for master Lean.

**Comment by Kha** [comment]
Actually, nevermind
```bash
$ ls lean_packages/*/build/lib/*.dll | wc -l
135
```

**Comment by Kha** [comment]
@tydeu Please open a separate issue if the Alloy issue persists
