### ISSUE TITLE
`congr` does not realize that opt-params are vacuous dependencies

### ISSUE THREAD

**Issue by gebner** [leanprover/lean4#1808]
The following used to work in Lean 3:
```lean
class Preorder (α : Type u) extends LT α :=
(le : α → α → Prop)
(lt_iff_le_not_le : ∀ a b : α, lt a b ↔ (le a b ∧ ¬ le b a) := by intros; rfl)

theorem Preorder.toLE_injective (A B : Preorder α) (h : A.le = B.le) : A = B := by
  cases A; cases B; cases h
  congr -- does not make progress, should produce a goal for `A.lt = B.lt`
```
(It's probably related to the subobject inheritance of `LT α`, the `congr` tactic makes progress if the `lt` field is inlined.)

**Comment by gebner** [comment]
Reported on Zulip: https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Equality.20of.20structures.20with.20autoparams/near/308446269

**Comment by leodemoura** [comment]
> It's probably related to the subobject inheritance of LT α, the congr tactic makes progress if the lt field is inlined.

Correct. 
```lean
theorem Preorder.toLE_injective (A B : Preorder α) (h : A.le = B.le) : A = B := by
  cases A; cases B; cases h
  rename LT α => lt; cases lt
  rename LT α => lt; cases lt
  congr -- makes progress
```

I can see this issue happening in many Mathlib proofs being ported to Lean 4. The flat representation used in the old Lean 3 structure command is ideal for `congr`.
The first idea/hack that comes to mind is special support in `congr` for structure constructors. I think it is a defensible hack since we try to provide the illusion that we have a "flat" representation in other places. What do you think?

**Comment by gebner** [comment]
Now I also see what's going on.  Yeah, special support for structure constructors in congr lemmas is the best O can think of too.

The issue also pops up with simp: https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/unfolding.20earlier.20fields/near/302587283
