### ISSUE TITLE
Dot notation on `where`-bound identifier fails

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#1850]
```lean
example : Nat :=
  let n := 0
  -- last one fails
  n.succ + (m |>.succ) + m.succ
where
  m := 1
```

**Comment by leodemoura** [comment]
We currently disable dot notation for (potentially) recursive declarations being defined. Recall that `where` is sugar for `let rec`.
The reason for this restriction are examples such as
```lean
def foo.aux := 1
def foo : Nat → Nat
  | n => foo.aux -- We don't want `foo.aux` to be interpreted as `(foo).aux`
```
The example above looks artificial, but we had the following issue in the past
```lean
namespace Precategory
  inductive Arity : Type
    | left | right | mul | bottom

  def signature : Sum Arity 𝟎 → Nat := ...
end Precategory

def Precategory : Type (u + 1) :=
  Alg.{0, 0, u, 0} Precategory.signature  --- HERE
```
Possible improvement: instead of disallowing dot notation for potentially recursive declarations being defined, we just stop the local name resolution if there is a global name that would be shadowed. Cons: some users may find it confusing.

**Comment by Kha** [comment]
Thanks for the explanation, I didn't even consider this interaction.

> Cons: some users may find it confusing.

I'm relatively certain it would be an improvement in the eyes of a majority, users do not think of `foo` as a local variable. On the flip side, users may not think of a `where`-bound name as something that eventually becomes a global decl, but in that case collisions with the environment seem incredibly unlikely anyway.
