### ISSUE TITLE
outParam on instances

### ISSUE THREAD

**Issue by riccardobrasca** [leanprover/lean4#1852]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The following
```lean
class foo (F : Type) where
  foo : F

class foobar (F : outParam Type) [foo F] where
  bar : F
```
gives the error
```bash
invalid class, parameter #2 depends on `outParam`, but it is not an `outParam`
```

It can be fixed writing
```lean
class foo (F : Type) where
  foo : F

class foobar (F : outParam Type) [outParam (foo F)] where
  bar : F
```
but in  Lean3 this was not necessary.

I don't know if this is the expected behavior, but it looks worse than in Lean3.

**Comment by leodemoura** [comment]
> I don't know if this is the expected behavior, but it looks worse than in Lean3.

My interpretation is: you prefer Lean 4 to silently treat implicit arguments that depend on other `outParam` as `outParam`s, correct?
If yes, could you please confirm with other users whether they are happy with this change?

**Comment by digama0** [comment]
My 2c on this issue is that, for the case of instance implicit args specifically, it is already assumed that they are searched only after all of their (non-outParam) arguments are ready. Since `F` is not an outParam of `foo` in this example, that means that we would normally expect instance search of `[foo F]` to happen only after `F` is available, which means that it is already logically an outparam.

So I think we should silently / automatically upgrade these instance arguments to outparams without requiring an annotation. For regular variables I think the error message makes sense and should stay.
