### ISSUE TITLE
Can't use '' as infix operator

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#1922]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

We'd like to use `''` as an infix operator in mathlib; we use it for the image of set. However it generates a `missing end of character literal` whenever used:

### Steps to Reproduce

```lean
def Set (α : Type u) := α → Prop

def image (f : α → β) (s : Set α) : Set β :=
  fun b => ∃ a, s a ∧ f a = b

infixl:80 " '' " => image

example {f : α → β} {s : Set α} {y : β} : f '' s = f '' s := rfl -- Errors on `f '' s` with `missing end of character literal`.
```

**Expected behavior:** 

No error.

**Actual behavior:**

`missing end of character literal`

### Versions

Lean (version 4.0.0-nightly-2022-12-05, commit 0b243f0ca33e, Release)

### Additional Information

As reported in [zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/data.2Eset.2Ebasic/near/314346400).

**Comment by kbuzzard** [comment]
I think it's worth remarking that although `''` is standard mathlib notation, it's not actually standard mathematical notation (despite Mario's claims that he saw it in a book once), so perhaps our instinct "please let us keep our nonstandard notation which we're used to" could be turned into "maybe we can fall in love with a new notation" if this issue is actually problematic. If you could make standard maths notation `f(S)` work (here `f : X->Y` and `S : set Y`) that would be even better ;-)

**Comment by digama0** [comment]
@Kha I think the quick solution is better for the immediate issue (we had to add a workaround for the port but it would be good to remove it before we forget). The "thorough" solution sounds like a bit of a project and I think only you would be able to do it, so I'd rather not bank on it but please try it if you are motivated to do so.
