### ISSUE TITLE
Huge terms have huge popups

### ISSUE THREAD

**Issue by gebner** [leanprover/lean4#2052]
I realize that this is a bit of a "you get what you asked for" situation, but Kevin complained about this on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/can't.20read.20.22popup.20boxes.22.20sometimes/near/322609275).  And he's got a point: you can't practically use the popups if the subterm is too large.  Not even to inspect implicit arguments.

```lean
def N : Nat := Nat.add 37 50

example : N ≠ N := by
  simp (config := {decide := false}) only [N, Nat.add]
  /- Put cursor on outermost `Nat.succ` in infoview -/
  sorry
```

The popup is so large (multiple pages) that you can't see what the top-level function symbol is, or what the implicit arguments are.

(Note: this issue is not about missing scrolling, clipped overflow, or other CSS issues in the infoview.  This issue is about what data we send to the editor.  And the editor can't really make this data any smaller.)

**Comment by Vtec234** [comment]
I guess the obvious solution would be to start collapsing terms whose size exceeds some configurable threshold, and to make them lazily openable.

**Comment by gebner** [comment]
Yeah, that's also what I've been thinking of as well.

**Comment by kbuzzard** [comment]
Note that https://github.com/leanprover/vscode-lean4/pull/289 is a PR which claims to fix this issue. 

By the way, a far less pathological way of getting a huge popup is to hover over an `=` in the infoview, because the docstring for `=` is ridiculously long. It can often be difficult to see what the type of the terms `x` and `y` are if your goal is `x = y`. 

![Screenshot from 2023-05-30 22-30-25](https://github.com/leanprover/lean4/assets/31867827/aad249f6-3fce-454d-b615-fe55c7ec12e4)

**Comment by leodemoura** [comment]
We now have `set_option pp.deepTerms false`

**Comment by leodemoura** [comment]
@mhuisi Should we close this issue?

**Comment by mhuisi** [comment]
Yes, I think that's fine.
