### ISSUE TITLE
Confusing error message with unassigned metavariables

### ISSUE THREAD

**Issue by gebner** [leanprover/lean4#2058]
```lean
def sameHere : Nat :=
  let x := [] -- invalid occurrence of universe level 'u_1' at 'sameThing', ...
  42
```

Ideally we'd:
 - complain about the unassigned metavariable for the type instead (like we would do if lists weren't universe polymorphic), and
 - add the `sameHere` definition to the environment anyhow (like we would do if lists weren't universe polymorphic).

**Comment by david-christiansen** [comment]
This issue affects me basically every day, though I may be a bit atypical in this regard - I write lots of monadic code, and lots of loops that assemble an output by mutation.

In particular, writing programs like this causes the issue to show up:
```
example : IO Unit := do
  let mut x := none
  pure ()
```
```
example : IO Unit := do
  let mut output := []
  pure ()
```
```
example : IO Unit := do
  let mut output := #[]
  pure ()
```

These programs occur not only when writing new code, they also show up when refactoring existing code. Adding e.g. a mutation of `output` further down in the function makes the error go away, but deleting it (perhaps months later) causes it to return. What's worse - the error is shown on the first line of the definition, not the binder in question. Because the source location is not precise, it can be tricky to track down the error even knowing what causes it, and the precise text of the message includes lots of concepts that new users may not know about.

@gebner's suggested improvements here, essentially treating it like any other situation with an ambiguous type, would make a big difference.

**Comment by david-christiansen** [comment]
Though I'd add a third point to the desiderata for a solution:

 * The source location of the error should be the binding with the unsolved meta

This code here is not universe-polymorphic:
```

example : IO Unit := do
  let mut x := pure (f := IO)
  pure ()
```
It highlights `x` with `failed to infer 'let' declaration type` and `pure (f := IO)` with `don't know how to synthesize implicit argument 'α'`, which is much more actionable.
