### ISSUE TITLE
`linter.unusedVariables` false positive in dependent types

### ISSUE THREAD

**Issue by ghost** [leanprover/lean4#2088]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description
The linter warns about an unused variable which _is_ used, in the type of a variable introduced with the `variable` command (in certain circumstances).

### Steps to Reproduce
```lean
variable (α : Type _) {β : α → Type _}
variable (β) (γ : {a : α} → β a → Type _)
```

**Expected behavior:** no unused-variable warning for `a`.

**Actual behavior:** unused-variable warning for `a`.

**Reproduces when:** this warning only occurs (roughly) when the argument `a` to `γ` is not explicit, and certain other variables (in these examples, it's always the corresponding `β`) have been updated from explicit to implicit/etc. before it in the same `variable` command.

```lean
variable (α₁ : Type _) {β₁ : α₁ → Type _}
-- (currently) warning
variable (β₁) (γ₁ : {a : α₁} → β₁ a → Type _)

variable (α₂ : Type _) (β₂ : α₂ → Type _)
-- (currently) warning
variable {α₂ β₂} (γ₂ : ⦃a : α₂⦄ → β₂ a → Type _)
-- no warning
variable {α₁} ⦃γ₂⦄ (γ₂' : ⦃a : α₂⦄ → β₂ a → Type _)

variable (α₃ : Type _) (β₃ : α₃ → Type _)
-- (currently) warning, but only if it's placed
-- before the next test, not if it's placed after...
variable {β₃} (γ₃ : {a : α₃} → β₃ a → Type _)

class α₄ variable (β₄ : α₄ → Type _)
-- (currently) warning
variable ⦃β₄⦄ (α₁) (γ₄ : [a : α₄] → β₄ a → Type _)

variable (α₅ : Type _) {β₅ : α₅ → Type _}
-- no warning
variable (β₅) (γ₅ : (a : α₅) → β₅ a → Type _)
```

### Versions
`4.0.0-nightly-2023-02-03` (commit d4b9a532d235), on Linux.

**Comment by nomeata** [comment]
Also affecting https://github.com/leanprover-community/mathlib4/pull/1942. Once fixed, please someone check if `Mathlib/Data/Dfinsupp/Order.lean` can be linted again.

**Comment by int-y1** [comment]
I wrote a workaround for https://github.com/leanprover-community/mathlib4/pull/1942. The linter thought `i` was unused in:

```
variable (α) [∀ i, Zero (α i)]
```

The workaround was:

```
variable (α)
variable [∀ i, Zero (α i)]
```

**Comment by leodemoura** [comment]
The `lean-auto` package seems to trigger many instances of this bug. Here is one:
https://github.com/leanprover-community/lean-auto/blob/7f4beaa6b1cdcee075f0e91a0da9705ecd3e3107/Auto/Embedding/LamSystem.lean#L594

**Comment by digama0** [comment]
I think the lean-auto bug is different, this has to do with `_` variables in match not suppressing the unused variable warning. Std also has many instances of this issue, the usual workaround is to use `_x` instead of `_`.

The examples in the OP here seem to have to do with the funky elaboration state used by `variable`, I think it is related to [this zulip issue](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Tactic.20is.20never.20executed/near/400227495) and #2226. (In general, issues with `unusedVariables` linter are usually not actually linter issues but rather the most obvious sign that there is a bug in elaboration and/or the info tree generation, which generate the correct term but with the wrong auxiliary info.)

**Comment by Kha** [comment]
Does not reproduce anymore, likely fixed by the `variable` revamp
