### ISSUE TITLE
"Significant Changes" Documentation Missing Removal of "variables"?

### ISSUE THREAD

**Issue by pwintz** [leanprover/lean4#2228]
In the Lean 3 documentation, there are examples that use the `variables` comma, such as `variables (p q : Prop)` found [here](https://leanprover.github.io/reference/expressions.html). When I try to use this expression in Lean 4, however, and error says, "Expected command." Was `variables` removed from Lean? If so, it should be added to "[Significant changes from Lean 3](https://leanprover.github.io/lean4/doc/lean3changes.html#significant-changes-from-lean-3)".

Same with `universes`?

**Comment by digama0** [comment]
If you use mathlib, you will get a message saying
```
'variables' has been replaced by 'variable' in lean 4
```

**Comment by pwintz** [comment]
@digama0 Thanks, that's as I suspected. Another piece of code from the Lean 3 manual that doesn't work in Lean 4 and is not documented in the "changes" page is
* [`let x := 5 in x + 3`](https://leanprover.github.io/reference/expressions.html#computation)?

**Comment by PatrickMassot** [comment]
@pwintz I think you missed the word "Significant" in the title of this section. That webpage cannot list every difference between Lean 3 and Lean 4. The things you complain about are tiny syntax changes, there are hundreds of those.

**Comment by pwintz** [comment]
Those "tiny syntax changes" cause code from Lean 3 to not compile in Lean 4. Any change that breaks backward compatibility is significant and should be documented _somewhere_.

**Comment by pwintz** [comment]
For context, I'm reading through [Lean 3 documentation](https://leanprover.github.io/reference/declarations.html) because I couldn't find a comparable reference for Lean 4 (the manual found [here](https://leanprover.github.io/lean4/doc/whatIsLean.html) omits any comprehensive description of declarations, expressions, etc.). It's frustrating needing to guess what the problem and solution are each time a Lean 3 example fails to compile. A comprehensive change log would solve that problem.

**Comment by digama0** [comment]
You should be using https://github.com/leanprover-community/mathport to translate lean 3 projects to lean 4. This tool knows about every single syntax change that exists. But in documentation, it is more high level than that because there are just too many changes to reasonably present. Hence "Significant changes". Most of the minor syntax changes are obvious just by looking at lean 4 code, assuming you know lean 3.

**Comment by pwintz** [comment]
But I **don't** know Lean 3, and I don't want to have to run the Lean 3 documentation through Mathport each time I try to read an example. 

The root of the problem is that the documentation for Lean 4 seems half-baked, forcing me to rely on Lean 3 documentation to learn Lean. This is a pretty significant barrier to entry for newcomers. You can take or leave my suggestion to clarify the "significant changes" documentation, but I thought you would like to know that the current document is missing important info that makes it less helpful.

**Comment by digama0** [comment]
> But I **don't** know Lean 3, and I don't want to have to run the Lean 3 documentation through Mathport each time I try to read an example.

The solution to *this* problem is to improve the documentation for lean 4. Most of the lean 3 documentation sources are in some state of translation. If you would like to help make the documentation less "half-baked" perhaps it would be better to open an issue about that instead of documentation about migration from a language you don't use.
