### ISSUE TITLE
String.toName doesn't strip french quotes.

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#2231]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

`String.toName` doesn't strip French quotes.

### Steps to Reproduce

```
import Lean

#eval "«hello»".toName
```

**Expected behavior:**

Should print ```hello``.

**Actual behavior:**

Prints ```«hello»``.

### Versions

Lean (version 4.0.0-nightly-2023-05-16, commit ebc32af2e606, Release)

**Comment by eric-wieser** [comment]
Another good test-case:
```
#eval "«hello.world»".toName = `«hello.world»
```

**Comment by gebner** [comment]
Oh yeah, `String.toName` is a big footgun and you shouldn't use it.  The "proper" way to turn a string into a name is `Syntax.decodeNameLit ("`" ++ s)`.  This is e.g. how the JSON deserializer does it.

It would be great to split `Syntax.decodeNameLit` into two functions though, so that you don't need to prepend the backtick.

**Comment by digama0** [comment]
> It would be great to split `Syntax.decodeNameLit` into two functions though, so that you don't need to prepend the backtick.

...and maybe call that function `String.toName`.
