### ISSUE TITLE
RFC: Using the Lean `Frontend` to compile multiple modules

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#2408]
Both @adamtopaz and I have recently been trying to use functions from `Lean.Elab.Frontend` to compile files from `Mathlib`.

In my case it is to extract data from `InfoTree`s (e.g. with to export all goal/tactic pairs in the library, or answer questions like "of goals currently closed by `aesop`, how many are solvable by `my_other_tactic`).

In a recent [zulip thread](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/difficulties.20with.20.60Frontend.60) we've both reported similar difficulties. This issue summarises the problems, with a reproducible test case.

## To reproduce

A minimized version of this is set up as a test in #2407, which of course [currently fails](https://github.com/leanprover/lean4/actions/runs/5830058402/job/15810685857?pr=2407#step:11:4153).

You can put the following file into either `Mathlib`, or any project depending on `Mathlib`.

```lean
-- Save as "Frontend.lean"
import Lean.Elab.Frontend

open Lean Elab

unsafe def processInput (input : String) (initializers := false)  :
    IO (Environment × List Message) := do
  let fileName   := "<input>"
  let inputCtx   := Parser.mkInputContext input fileName
  if initializers then enableInitializersExecution
  let (header, parserState, messages) ← Parser.parseHeader inputCtx
  let (env, messages) ← processHeader header {} messages inputCtx
  let s ← IO.processCommands inputCtx parserState (Command.mkState env messages {}) <&> Frontend.State.commandState
  pure (s.env, s.messages.msgs.toList)

open System in
def findLean (mod : Name) : IO FilePath := do
  return FilePath.mk ((← findOLean mod).toString.replace "build/lib/" "") |>.withExtension "lean"

/-- Read the source code of the named module. -/
def moduleSource (mod : Name) : IO String := do
  IO.FS.readFile (← findLean mod)

unsafe def compileModule (mod : Name) (initializers := false) :
    IO (Environment × List Message) := do
  processInput (← moduleSource mod) initializers

unsafe def main (args : List String) : IO Unit := do
  initSearchPath (← findSysroot)
  let mut initializers := false
  match ← IO.getEnv "LEAN_INITIALIZERS" with
  | some "ONCE" =>
    IO.println "Invoking `enableInitializersExecution` once at the beginning."
    enableInitializersExecution
  | some "EACH" =>
    IO.println "Invoking `enableInitializersExecution` at each compilation."
    initializers := true
  | _ =>
    IO.println "Not invoking `enableInitializersExecution`"
  for mod in args do
    IO.println s!"Compiling {mod}"
    let (_, msgs) ← compileModule mod.toName initializers
    for m in msgs do IO.println (← m.toString)
```

and add it to your `lakefile` with the entry:
```
lean_exe «frontend» {
  root := `Frontend
}
```

## Usage

Now the command `lake exe frontend module1 ... modulen` will try to compile the named modules, one after the other.
The goal is to be able to run this on an arbitrary subset of modules from Mathlib. (Although having a limitation such as requiring a topological sort of the import graph would not be serious obstacle.) However at the moment I can only get this to work on a single module at a time.

Further, we can control when `enableInitializersExecution` is run, using an environment variable `LEAN_INITIALIZERS`, set to `ONCE`, `EACH`, or `NONE`.

* For `ONCE`, we execute `enableInitializersExecution` once, before starting to compile anything.
* For `EACH`, we execute `enableInitializersExecution` before compiling each file.
* For `NONE`, we don't run it at all.

## Results

* `NONE` simply doesn't work at all:

```
% LEAN_INITIALIZERS=NONE lake exe frontend Mathlib.Algebra.Abs
Not invoking `enableInitializersExecution`
Compiling Mathlib.Algebra.Abs
libc++abi: terminating with uncaught exception of type lean::exception: cannot evaluate `[init]` declaration 'Mathlib.Prelude.Rename.linter.uppercaseLean3' in the same module
```

* `ONCE` works on any single file, but not on any two files:

```
% LEAN_INITIALIZERS=ONCE lake exe frontend Mathlib.Algebra.Abs
Invoking `enableInitializersExecution` once at the beginning.
Compiling Mathlib.Algebra.Abs

% LEAN_INITIALIZERS=ONCE lake exe frontend Mathlib.Algebra.AddTorsor
Invoking `enableInitializersExecution` once at the beginning.
Compiling Mathlib.Algebra.AddTorsor

% LEAN_INITIALIZERS=ONCE lake exe frontend Mathlib.Algebra.Abs Mathlib.Algebra.AddTorsor
Invoking `enableInitializersExecution` at each compilation.
Compiling Mathlib.Algebra.Abs
Compiling Mathlib.Algebra.AddTorsor
libc++abi: terminating with uncaught exception of type lean::exception: cannot evaluate `[init]` declaration 'Mathlib.Tactic.reflExt' in the same module
```

* `EACH` works on any single file (because it is equivalent then to `ONCE`!) and fails with a different error message when run on any two files:

```
% LEAN_INITIALIZERS=EACH lake exe frontend Mathlib.Algebra.Abs Mathlib.Algebra.AddTorsor
Invoking `enableInitializersExecution` at each compilation.
Compiling Mathlib.Algebra.Abs
Compiling Mathlib.Algebra.AddTorsor
PANIC at Lean.PersistentHashMap.find! Lean.Data.PersistentHashMap:160:14: key is not in the map
...
<input>:6:0: error: invalid option declaration 'linter.uppercaseLean3', option already exists
...
```
(Many copies of the PANIC, and many subsequent errors, have been snipped.)

## Minimization

A minimal set of files to observe this behaviour is:

```
-- Save as "Frontend/RegisterOption.lean"
import Lean

register_option option : Bool := {
  defValue := true
  descr := ""
}
```

```
-- Save as "Frontend/Import1.Lean"
import Frontend.RegisterOption
```

```
-- Save as "Frontend/Import2.Lean"
import Frontend.RegisterOption
```

and then run
```
% LEAN_INITIALIZERS=EACH lake exe frontend Frontend.Import1 Frontend.Import2
Invoking `enableInitializersExecution` at each compilation.
Compiling Frontend.Import1
Compiling Frontend.Import2
<input>:1:0: error: invalid option declaration 'option', option already exists
```

## Discussion

Up for discussion:
* Do we really need this? Is working one file at a time manageable?
* Are there ways to achieve this goal with the existing code?
* @digama0 has suggested a change that addresses this issue https://github.com/leanprover/lean4/pull/2398, but requires a change to Lean 4. With that we have:

```
-- % LEAN_INITIALIZERS=REINIT lake exe frontend Mathlib.Algebra.Abs Mathlib.Algebra.AddTorsor
-- Invoking `enableInitializersExecution` and `enableReinitialization` at each compilation.
-- Compiling Mathlib.Algebra.Abs
-- Compiling Mathlib.Algebra.AddTorsor
```

I've grafted the failing test from #2407 onto that PR, and modified it to use `enableReinitialization`.

**Comment by gebner** [comment]
What do you want to do about tools that assume that there's only one module per process (like library search which assumes the imports never change).  Or about global variables like the list of attributes, or the built-in parsers/elaborators/etc., or trace classes etc.?  All of these could break elaboration if you load more modules than those that are explicitly imported.  (And of course on mathlib-scale, could means it will on at least one file.)

Can you elaborate on what tools this would enable?  In my experience, the main bottleneck is needing to elaborate the files to access the info trees.  Running the initializers (what #2398 enables) is only a fraction of the import time (which is IIRC dominated by constructing the discrimination tree for the simp set, and building the name→declaration hash map).  Elaborating the file itself is orders of magnitude slower still.

> In my case it is to extract data from InfoTrees (e.g. with to export all goal/tactic pairs in the library, or answer questions like "of goals currently closed by aesop, how many are solvable by my_other_tactic).

Both of these applications seem more easily solved by running one process per file and then concatenate the results.  (Which also means you can trivially parallelize it.)

**Comment by digama0** [comment]
> Running the initializers (what https://github.com/leanprover/lean4/pull/2398 enables) is only a fraction of the import time (which is IIRC dominated by constructing the discrimination tree for the simp set, and building the name→declaration hash map). Elaborating the file itself is orders of magnitude slower still.

The purpose of #2398 was not to improve the performance but just to make it *possible* to run elaboration more than once in the same process. This was a problem for me even when driving lean from a non-lean program which does not use the lean lifecycle for elaboration (e.g. a rust library that allows clients to elaborate lean files). As long as the IO refs are reset every time you re-elaborate it's fine, but initializers are especially pernicious in this regard because there is no way to unset the initializers. 

If there are other bits of code here and there using global state they might also need review, but initialization is specifically important because without initialization you can't call any lean code at all, even if you aren't running the elaborator. I think most of the examples you give are only a problem for `builtin_initialize`, and in this case the list will already contain things from outside the current environment (since it has everything from the previous stage).

**Comment by gebner** [comment]
> This was a problem for me even when driving lean from a non-lean program which does not use the lean lifecycle for elaboration (e.g. a rust library that allows clients to elaborate lean files).

My point is that this usage is just not supported at all, because importing modules changes the global state.  And that this is the reason why nobody bothered to support reinitialization.

An additional complication that I just remembered is multi-threading.  Most initializers expect to run single-threadedly, and before any other Lean code is executed.  For example adding an environment extension will cause out-of-bounds accesses on existing environment objects.

> the examples you give are only a problem for `builtin_initialize`

You are correct for elaborators and parsers, the rest uses initializers always.  (Attributes, parser aliases, environment extensions, trace classes, etc.)

**Comment by digama0** [comment]
> My point is that this usage is just not supported at all, because importing modules changes the global state. And that this is the reason why nobody bothered to support reinitialization.

I'm aware of this, that's why the title was "basic support for reinitialization". The assumptions run deep but maybe we can fix some of the most obvious issues. I don't think it is long term sustainable for lean as a general purpose programming language to not be able to support either resetting global state or making it less global. (Another application that I now remember hit this issue was lean REPL, it really wants to be able to reset the state without exiting the process.)

**Comment by gebner** [comment]
> Another application that I now remember hit this issue was lean REPL, it really wants to be able to reset the state without exiting the process.

Without even touching the REPL API, there is no reason why it couldn't spawn a subprocess every time you send it an `import ...` command.  (Just like the LSP server and mathport already do.)

**Comment by digama0** [comment]
One reason is because there is other state (e.g. for the REPL itself) which is persisted between files. With the current architecture you can't have cross-session data and lean environment objects (or anything depending on them) living in the same process, unless you use an RPC protocol (with its attendant restrictions regarding e.g. closure objects). If it's a clean wipe you may as well just quit the process itself and restart it.
