### ISSUE TITLE
scoped `[macro]` attribute 

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#249]
and `scoped macro_rules`.
Users may override a built-in notation using `macro_rules`.
We currently do not support `[scoped macro]` or `scoped macro_rules`. So, the following is not supported
```lean
namespace Foo
-- Redefine a bunch of builtin notation using scoped attributes
-- ...
end Foo
...
open Foo -- activate customization above
```

**Comment by tydeu** [comment]
Now that the `[scoped macro]` attribute exists, adding `scoped macro_rules` should just involve adding an optional `attrKind` to the syntax and transferring that kind down to the `[macro]` attribute during elaboration, correct? If so, I would volunteer to handle this issue (if desired).

**Comment by Kha** [comment]
Yes, you can also take a look at `scoped macro` (the *command*, which I didn't know we already had!). Please also add a test, e.g. in `tests/lean/scopedMacros.lean`.

**Comment by leodemoura** [comment]
@kha the `scoped` in `scoped macro` is just affecting the generated syntax. We don't have scoped support for `macro_rules` yet.

**Comment by tydeu** [comment]
@leodemoura For a `scoped macro` command, should the associated `macro_rules` even be scoped? Since the rules are tied to an already scoped `syntax` kind, they will only be applied when that kind is in scope. Thus, I am not sure that scoping the rules there is necessary/desired, and I, personally, would not scope them

**Comment by tydeu** [comment]
FYI @Kha / @leodemoura , this issue should probably be closed.
