### ISSUE TITLE
`lake +xyz new foo` should use `xyz` in `foo/lean-toolchain`

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#2518]
Currently if `xyz` here is a PR toolchain (i.e. of the form `leanprover/lean4-pr-releases:pr-release-NNNN`) then `lake` doesn't produce any `lean-toolchain` file.

1. Any condition that results in`lake new` not producing a `lean-toolchain` should prominently warn the user that it has produced an unusable project, explaining why.

2. This failure is because `lake` relies on `Lean.toolchain` being set, but setting `Lean.toolchain` in PR releases would be complicated (we can do it if necessary, but it requires adding extra epicycles to the CI). It would be easier if we could just take the user's intention indicated through `+xyz` and give them that toolchain directly.

**Comment by tydeu** [comment]
> 1. Any condition that results in`lake new` not producing a `lean-toolchain` should prominently warn the user that it has produced an unusable project, explaining why.

This would be rather annoying in any dev setup as this warning would always be printed. But, luckily, `lake init` isn't used too often in such contexts so that should not be to much trouble.

> 2. This failure is because `lake` relies on `Lean.toolchain` being set, but setting `Lean.toolchain` in PR releases would be complicated (we can do it if necessary, but it requires adding extra epicycles to the CI). It would be easier if we could just take the user's intention indicated through `+xyz` and give them that toolchain directly.

The `+xyz` is part of elan's Lake wrapper, not part of Lake, so Lake has no access to it. Changing this thus requires a change to elan. Perhaps it could set the `LEAN_TOOLCHAIN` environment variable to the relevant toolchain when running processes?

**Comment by Kha** [comment]
> Perhaps it could set the `LEAN_TOOLCHAIN` environment variable to the relevant toolchain when running processes?

We already have something like that: https://github.com/Kha/elan/blob/7d94a1fb806d978563f07bb0760d3bcce7a7f6f4/src/elan/toolchain.rs#L227
