### ISSUE TITLE
Delaboration of re-exported names

### ISSUE THREAD

**Issue by hargoniX** [leanprover/lean4#2524]
### Description

Delaborating things that contain names of re-exported types can chose the wrong name for the type.
This most notably causes incorrect doc-gen4 renders: https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Confusing.20delaboration.20in.20.20doc-gen/near/388158478

### Steps to Reproduce

Delaboration of `Lake.Name`:
```lean
import Lean
import Lake

#eval show Lean.MetaM _ from do
  let ⟨fmt, _⟩ ← Lean.PrettyPrinter.ppExprWithInfos (Lean.mkConst ``Lean.Name)
  println! fmt
```

Further minified:
```lean
import Lean
import Lake

open Lean
#eval show MetaM _ from do
  unresolveNameGlobal ``Name
```

**Expected behavior:** We get `Lean.Name`

**Actual behavior:** We get `Lake.Name`

**Reproduces how often:** Always

**Comment by Kha** [comment]
@tydeu Let's just turn these into `abbrev`s? I'm not sure `export` is the right tool here. One of these names will always be printed as the other with it.

**Comment by tydeu** [comment]
@Kha Printing it always as `Lean.Name` would be what I would expect here. With `Lake.Name`, I am not trying to create a distinct type, but just have `Lean.Name` available when I `open Lake`.

**Comment by kmill** [comment]
I have two competing solutions to this problem:

1. Change Lake. #5688 removes the `export`s and adds the relevant `open` commands.
2. Change pretty printing. #5689 makes pretty printing only consider aliases into parent namespaces.

I'd prefer option 1 if @tydeu would accept it, but otherwise I'll leave it to @Kha and the triage team to decide which of these two solutions (if either) might be acceptable.

**Comment by tydeu** [comment]
@kmill I am fine with a temporary stop-gap measure,  but I would very much want this fixed in the future. Having to manually `open` common names is cumbersome. Forgetting to do so, can also lead to confusing problems with auto-implicits. Fortunately, your `scoped open` idea sounds like great solution!
