### ISSUE TITLE
`simp` fails when custom discharger makes no progress

### ISSUE THREAD

**Issue by fpfu** [leanprover/lean4#2634]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Steps to Reproduce

```
example
  {p: Prop}
  (h: True → p)
  : p := by 
  simp (discharger:= skip) [h]
```

**Expected behavior:** `simp` fails with message:

`simp made no progress` 

**Actual behavior:** `simp` fails with message: 

```
unsolved goals

case simp.discharger
p: Prop
h: True → p
⊢ True
```

### Versions

`nightly-2023-10-07`

### Additional Information

It's also would be useful to have an option to fallback to the default discharger when the custom provided one will be unable to close the goal. 

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by leodemoura** [comment]
@semorrison Could you please take a look? This seems to be a bug introduced when we recently modified `simp`.

**Comment by digama0** [comment]
This seems like it needs design work, because the indicated behavior is exactly what I would expect from the algorithm as implemented: it tries `h` as a rewrite rule, but `skip` doesn't close the subgoal so it is not considered, hence nothing is rewritten and simp fails with no change. What is the expected behavior here?

The only other behavior I can imagine is for the subgoal to be returned as an additional side goal and the rewrite treated as a success (in which case the default discharger should be `simp; done` rather than `simp`), but this would make any conditional rewrite apply unconditionally (at least when you use `skip` as the discharger), so you would likely get random subgoals from the first thing to apply when using `simp` with the whole default simp set as in this example.

**Comment by fpfu** [comment]
As far as I understand, actual behavior is that there is a "leaking" temporary metavariable in function `Lean.Elab.Tactic.tacticToDischarge` that produces unexpected error even when `simp` should succeed.

Consider following examples:

```lean
example
  {p q: Prop}
  (h₁: True → p)
  (h₂: q = p)
  : q := by 
  simp (discharger:= skip) only [h₁, h₂]
  sorry

example
  {p q: Prop}
  (h₁: True → p)
  (h₂: q = p)
  : q := by 
  simp only [h₂]
  sorry
```

Both uses of `simp` should succeed, leaving `⊢ p` as a target, but the first one produces `unsolved goals` error instead.

**Comment by semorrison** [comment]
I think @digama0 may have flipped the "expected" and "actual" behaviours when reading you report. Indeed we would like to see `simp made no progress`, but that's not what is happening.

**Comment by semorrison** [comment]
@leodemoura the same behaviour was present at 736a21cd5a, i.e. before the `failIfUnchanged` flag was added to `simp`.

My understanding of this issue is that `tacticToDischarge` in `src/Lean/Elab/Tactic/Simp.lean` uses `withoutModifyingStateWithInfoAndMessages`, and `Term.runTactic` is generating the "unsolved goals" message.

Possible solutions:
1. I'm not certain why we are using `withoutModifyingStateWithInfoAndMessages` rather than just `withoutModifyingState`. This isn't explained in the source, and there are no tests that care, according to #2640.
2. Modify `runTactic` so we can ask it not to call `reportUnsolvedGoals`, but instead just fail?
