### ISSUE TITLE
PR releases release (unwanted) merge state

### ISSUE THREAD

**Issue by nomeata** [leanprover/lean4#2701]
This is a follow up to https://github.com/leanprover/lean4/issues/2441

The PR releases are great! But I think they don’t release what they should.

Today, I pushed https://github.com/leanprover/lean4/pull/2577/commits/cf120acb2c43f3922ac2a2c9115b3353269060ff to https://github.com/leanprover/lean4/pull/2577/. This commit is behind the latest `master` (intentionally; I want the delta to `v4.2.0-rc2` small for sensible benchmarks). 

The release at <https://github.com/leanprover/lean4-pr-releases/releases/tag/pr-release-2577> however isn't built from `cf120acb2c43f3922ac2a2c9115b3353269060ff`, but rather from a synthetic merge commit with lean’s latest `master`, namely <https://github.com/leanprover/lean4-pr-releases/commit/96a003904b50ebd7e08c6e2228b202ec57cd6668> which does not exist on any branch, and has 

> Merge https://github.com/leanprover/lean4-pr-releases/commit/cf120acb2c43f3922ac2a2c9115b3353269060ff into https://github.com/leanprover/lean4-pr-releases/commit/44416624904d389f6fb2cddf018594d34624b2bf

as the commit message.

Looking at <https://github.com/semorrison/lean4/blob/master/.github/workflows/pr-release.yml> it seems the issue isn’t actually with this job; this job simply uses the commit that was tested by CI.  The problem is thus with <https://github.com/semorrison/lean4/blob/master/.github/workflows/ci.yml> using `actions/checkout@v3`:

That action has the very annoying default to not check out the tested branch as it is, but rather as it would look like if it were merged into `master` at that particular point (see https://github.com/actions/checkout#Checkout-pull-request-HEAD-commit-instead-of-merge-commit for docs). This is of course going to be very confusing: The CI results and the toolchain obtained this way describe some rather arbitrary state that depends on both the branch and `master` at the time it runs, and will be something else at some later time, even if the branch hasn’t changed. (Note that Github does _not_ update the CI status when `master` evolves, so this logic is surprisingly broken for a default.)

If others agree that this is a problem then my suggested way to fixing this would be to make all CI jobs test the head commit of the feature branch, and _not_ some merge state, and additionally enable “strict merges” so that only PRs that are up-to-date with regard to master can be merged.

**Comment by nomeata** [comment]
I guess I should @semorrison since it is related to #2441.

**Comment by semorrison** [comment]
@nomeata, I agree this is a problem.

We also need to consider how we should construct the Mathlib testing branches `lean-pr-testing-NNNN`. Currently every time a `lean-pr-testing-NNNN` toolchain is created, we merge Mathlib's `nightly-testing` into `lean-pr-testing-NNNN`, and try that.

Obviously this is an approximation that is only certain to work if:
* The PR NNNN is up to date with respect Lean `master`
* Mathlib's `nightly-testing` compiles against `master`

Further, of course I don't actually attempt to keep Mathlib's `nightly-testing` working against `master`: only against the latest nightly release.

While your proposed change will definitely be an improvement for testing of individual PRs against ad-hoc projects, I'm worried it will make testing Mathlib worse, because we will be further away from the approximation that the PR is always update to date with `master`.

So far I'm only coming up with really complicated solutions, such as:
* for each new Lean PR, work out where it departs from the `master` branch, and find the two nightly release on either side of that. (Perhaps there isn't yet one after that.) Select either the one before or after. (*Which is better?*)
* look through Mathlib's `nightly-testing` branch to find some commits that use that particular nightly, and succeed (*Which of these?*)
* make the `lean-pr-testing-NNNN` branch by starting from that commit on `nightly-testing`, and setting the toolchain to `leanprover/lean4-pr-releases:pr-release-NNNN`.
* if the Lean PR is updated, and its point of departure from the `master` branch changes ... ?

It's clear that the integrated testing with Mathlib is both fragile and really useful. We need a plan that includes making it more robust.

**Comment by nomeata** [comment]
Indeed, this is all very messy :-).

I’ll ponder it a bit, but I agree there is no quick fix here.

**Comment by semorrison** [comment]
@nomeata, just making a clarification to your description above.

It's not really the `actions/checkout` action at fault here. It is just using the `GITHUB_SHA` as provided by github, which for a pull_request is as you describe (and as specified at https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request).

I am increasingly thinking that we want to change this behaviour, however.
