### ISSUE TITLE
RFC: release musl binaries

### ISSUE THREAD

**Issue by foxyseta** [leanprover/lean4#2931]
### Proposal

Releasing musl binaries would make much easier for users using musl-based distros to install Lean on their machines. In addition, most lightweight containers are generally based on a musl-based distro, too (Linux Alpine).

As Lean for is still under active, intense development, I suppose this could wait(?). Anyway, :+1: are very much appreciated.

### Community Feedback

Pitched this idea [on Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/musl.20binaries/near/403254843) previously. Waiting for feedback.

**Comment by TwoFX** [comment]
Thank you for opening this RFC. The triage team has considered this request, but we have decided that we do not want to release musl binaries for the time being. Our list of supported platforms is already quite long, and when changing the runtime it is already extremely time consuming to ensure that everything is working on every platform. In addition, Lean depends on libuv, and musl is only a [Tier 2 platform](https://github.com/libuv/libuv/blob/d4ab6fbba4669935a6bc23645372dfe4ac29ab39/SUPPORTED_PLATFORMS.md) for libuv, which means that a change in this dependency could mean that our CI stops working due to a problem that was not discovered upstream. At the moment we feel that our time is better spent making Lean better on a shorter list of platforms rather than maintaining Lean on a longer list of platforms.

We might revisit this at some point, but for now I'll close this RFC.

**Comment by foxyseta** [comment]
Hey, is there a way this could be revisited? One additional benefit would be non-bloated container images.

**Comment by nomeata** [comment]
I don't expect the core team to have cycles for this in the near future, sorry. Have you considered providing an unofficial build yourself?

**Comment by foxyseta** [comment]
Yeah, I can do that. When I build, I usually apply [the patch described here](https://github.com/microsoft/mimalloc/issues/1056) (the linked issue is about M$ shenanigans).

Is there a place where people can contribute community builds?

**Comment by nomeata** [comment]
Nothing official, but maybe if you create a GitHub repo with the build steps, local patches, and make releases there, it might be useful to some?

**Comment by foxyseta** [comment]
Alright, will do this when i have time. Thanks!

**Comment by nomeata** [comment]
Thanks!

**Comment by runxiyu** [comment]
@foxyseta Is there any progress on this? (No pressure of course)

Love the language but being able to use it on musl is a hard blocker

**Comment by foxyseta** [comment]
I gave this a try today but got stuck here: https://ci.codeberg.org/repos/16884/pipeline/8/3#L2928

Now sure what is causing this error 2. Would printing the contents of the generated `build.make` makefile help @nomeata ?
