### ISSUE TITLE
Bad interaction of `variable` and `induction`

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#310]
```lean
variable (xs : List Nat)

theorem foo : xs = xs := by
  induction xs
```
```
    unsolved goals
    case nil
    ⊢ [] = []

    case cons
    head✝ : Nat
    tail✝ : List Nat
     : tail✝ = tail✝ → tail✝ = tail✝
    ⊢ head✝ :: tail✝ = head✝ :: tail✝
```
Note the type of the (unnamed) IH. Its binder is in fact a `BinderInfo.auxDecl`, so the recursion support seems to be involved as well.

**Comment by Kha** [comment]
```
variable (xs : List Nat)

theorem foo : xs = xs := by
  induction xs <;> rfl
```
```
    fail to show termination for
      foo
    with errors
    structural recursion cannot be used

    well founded recursion has not been implemented yet
```

**Comment by leodemoura** [comment]
The following example produces the same error
```lean
variable (xs : List Nat)

theorem foo : xs = xs := by
  cases xs with
  | nil        => rfl
  | cons x xs  => rfl
```

**Comment by leodemoura** [comment]
`induction` and `cases` use the "revert-<do something>-intro" idiom. Here, they are reverting the `auxDecl` `foo : xs = xs`. 
We can "see" what is going on when we use the following options
```lean
variable (xs : List Nat)

set_option pp.auxDecls true
set_option trace.Meta.Tactic true
theorem foo : xs = xs := by
  cases xs with
  | nil        => rfl
  | cons x xs  => rfl
```

Lean 3 has a similar problem, but it is harder to trigger it because these auxiliary declarations are added only when we use equations. Recall that in Lean 4, all definitions are assumed to be potentially recursive. Here is the Lean 3 version
```lean
variable (xs : list nat)

def foo : unit -> xs = xs  
  | _ := by cases xs; refl. -- `cases` produces an error message saying `foo` cannot be reverted.
```

I think the Lean 3 "error-message" approach doesn't work for Lean 4 because we always create these `auxDecls` in Lean4. The best solution I found so far is to `clear` any `auxDecl`s that depends on variables being reverted.
