### ISSUE TITLE
6 tests fail on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [leanprover/lean4#3179]
[log](https://freebsd.org/~yuri/lean4-4.5.0-rc1-tests.log)

**Comment by digama0** [comment]
The error in `leanlaketest_buildArgs` seems to be because this check is wrong:

https://github.com/leanprover/lean4/blob/53af5ead5359eeb47e1c7a62381000337b5d04c0/src/lake/tests/buildArgs/test.sh#L6-L10

Is it correct to say that FreeBSD uses the same `sed` as `Darwin` even though the uname is different?

**Comment by digama0** [comment]
The `leanlaketest_serve` error is similar:

https://github.com/leanprover/lean4/blob/53af5ead5359eeb47e1c7a62381000337b5d04c0/src/lake/tests/serve/test.sh#L4-L8

is apparently needed because the `tail` command on mac doesn't have the `--pid` option. Presumably it has the same fix as the other one.
