### ISSUE TITLE
`lake init` should not write imports with French quotes unnecessarily.

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#3385]
`lake init foo` creates `Foo.lean` containing `import «Foo».Basic`, which is quite confusing, and unnecessary.

Could we avoid confusing new users and teaching them unhelpful habits by not using French quotes unless necessary.

**Comment by semorrison** [comment]
Relatedly, `lakefile.lean` is populated with unnecessary French quotes in `package` and `lean_lib`.

**Comment by tydeu** [comment]
@semorrison The French quotes in the imports can probably be removed because Lean does not parse keywords in import statements. In the Lake configuration file; however, it is not possible to know whether the names are keywords. This was the source of a previous bug ([lake#128](https://github.com/leanprover/lake/issues/128)) which was the reason for introducing the French quotes.

**Comment by semorrison** [comment]
What is the origin of this impossibility? Can't we just use a fixed blacklist?

**Comment by tydeu** [comment]
@semorrison Lean does add new keywords as time progresses and those new keywords would then break packages with those names. A possibly better solution (which was part of #3174) is to allow the specification of package names as strings. This way we do not have to worry about keywords at all.

**Comment by semorrison** [comment]
Strings sound great.
