### ISSUE TITLE
RFC: restrict codomain of `FVarSubst` to `FVarId`

### ISSUE THREAD

**Issue by JLimperg** [leanprover/lean4#3683]
### Proposal

`FVarSubst`s are currently defined as partial maps from `FVarId` to `Expr`. However, all uses of `FVarSubst` that I could find in core actually ensure that the `Expr` is an `FVarId`. This is because, as far as I can tell, `FVarSubst`s are used exclusively to track renaming of hypotheses.

If these observations are correct, I suggest to redefine `FVarSubst` as a partial map from `FVarId` to `FVarId`. This would clarify the purpose of `FVarSubst`s and would slightly simplify the implementation. I'd be happy to implement this change.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by digama0** [comment]
Note that lean core uses `Expr` quite a lot in locations where only an `FVarId` is required or produced. I believe the reason is as a performance optimization, because this avoids the need to recalculate the hash and other data fields which are implicitly stored in the `Expr`. Assuming that this is the case here as well, that would mean that implementing this RFC is just a matter of clarifying the documentation to assert that the codomain must only use fvars.

That said, I'm not entirely sure this assumption actually holds. IIRC, `rcases` had to handle `FVarSubst`s containing nontrivial exprs, because these can occur after a `cases` application which has performed subst on some inductive index.

**Comment by JLimperg** [comment]
> That said, I'm not entirely sure this assumption actually holds. IIRC, `rcases` had to handle `FVarSubst`s containing nontrivial exprs, because these can occur after a `cases` application which has performed subst on some inductive index.

Indeed, `cases` constructs a nontrivial `FVarSubst` [here](https://github.com/leanprover/lean4/blob/14654d802d8950f75a6a2113a7d6288dd2f6cb19/src/Lean/Meta/Tactic/Cases.lean#L199), so that scuppers the RFC as written. It would still be nice to either document the restriction on the other uses of `FVarSubst` or to add the restricted variant and use it in those cases. I've already written the restricted variant for Aesop, so would be happy to upstream it if there's demand.

> Note that lean core uses `Expr` quite a lot in locations where only an `FVarId` is required or produced. I believe the reason is as a performance optimization, because this avoids the need to recalculate the hash and other data fields which are implicitly stored in the `Expr`. Assuming that this is the case here as well, that would mean that implementing this RFC is just a matter of clarifying the documentation to assert that the codomain must only use fvars.

That's good to know, thanks. I had assumed that these were just holdovers from Lean 3. Though in some cases, e.g. `mkFreshExprMVar`, I don't think there's any performance to be gained with this trick.

**Comment by semorrison** [comment]
I think this can be closed? Please reopen or ping me if this is mistaken.
