### ISSUE TITLE
RFC: pp.showNumericNames

### ISSUE THREAD

**Issue by nomeata** [leanprover/lean4#3781]
### Proposal

I wonder if it would be useful to have a `pp.showNumericNames` option, `true` by default, that if off prints `?m.1235` as simply `?m` or maybe `?m._`.

The concrete use case is that I tried to include this in the test suite:
```
/--
error: invalid field notation, type is not of the form (C ...) where C is a constant
  takeWhile
has type
  (?m.165402 → Bool) → Array ?m.165402 → Array ?m.165402
-/
#guard_msgs in
#check Errors.takeWhile.induct
```
and the error message would quickly go out of sync.

(Of course it’s not a great error message, and I wonder whether lean couldn’t count metavariables afresh for each command, but that’s not the point).

I imagine if I could add
```
set_option pp.showNumericNames false in
```
here then this would help.

(The option name isn't particularly carefully chosen yet.)

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by nomeata** [comment]
@kmill, what do you think of this?

**Comment by kmill** [comment]
I've been trying to think of a solution to this problem for a while, and the three options I can think of are
1. Give `#guard_msgs` a way to write wildcards in the message (and maybe create a pp option to print metavariables with a wildcard so that the code action can set it when generating the expected message?)
2. Come up with a robust way to rename metavariables when pretty printing, using some method where the name map is tied to the command but where the name map persists across multiple delaborator calls. This all seems too fiddly and hard to make robust.
3. Erase numbers like with what you have here.

Maybe a variation would be to have a name map that is per delaborator call, but it's used for inserting tombstones. Like, print them as `?m✝`, `?m✝¹`, `m✝²`, etc. That way there's less of an expectation that these are the real deal and stable, and also you can tell apart different metavariables in the same pretty printed result.

Option name suggestion: `pp.mvars.uniqNum`

**Comment by kmill** [comment]
The tombstone printing idea will take some more thought (I think the only reliable way to do it would be to rename all the metavariables in the expression before printing, so that the names are coherent across different hovers of the same expression).
