### ISSUE TITLE
Revisiting TC subgoal ordering

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean4#381]
The current TC-subgoal-order situation is not ideal. Here is the problem:

- For some instances, subgoals must be solved L->R to avoid a subtle nested-TC loop. Moreover, the need to do this is not easily detectable, since it depends on cyclic interactions between the instance in question and other instances.

- For some instances, solving L->R is bad because it will try to solve e.g. `Field ?` before a downstream subgoal that would have resolved the metavariable.

The current approach is for all instances to default to L->R, but to allow a `@[inferTCGoalsRL]` annotation indicating that the goals should be solved R->L for a particular instance. The main downside of this approach is the burden on the user who needs to provide this annotation when necessary.

Every example that I know about that requires `@[inferTCGoalsRL]` requires it for the same reason, and it is easy to automatically detect these cases and to do the right thing. When an instance is applied yielding subgoals `[g₁, ..., gₖ]`, any subgoals that (a) contain metavariables and that (b) appear in downstream goals can be moved to the back of the list. Here is a draft commit implementing this: https://github.com/dselsam/lean4/commit/5e269797e20cfc40033d4e19a62407af7b772923. For performance reasons, it would be preferable to compute the "shelving" bits for each subgoal at instance declaration time.

**Comment by leodemoura** [comment]
@gebner Is this issue impacting Mathport?

**Comment by gebner** [comment]
Relevant discussions Zulip discussion: https://leanprover.zulipchat.com/#narrow/stream/147302-lean4-dev/topic/TC.20hell

The real win for right-to-left solving comes from an additional optimization, namely that we can skip arguments that have already already been assigned.  So if you have an instance with arguments `[_inst_1 : A α] [_inst_2 : @B α _inst_1]`, then we never even attempt to synthesize `A α` (because that instance is already filled in via unification).  This was a huge improvement in Lean 3: https://github.com/leanprover-community/mathlib/issues/1561#issuecomment-596134024

I don't think we really depend on right-to-left solving otherwise.  And the examples from that issues work in Lean 4.

**Comment by Kha** [comment]
> The real win for right-to-left solving comes from an additional optimization, namely that we can skip arguments that have already already been assigned.

I assume the same reservations as in #952 apply here?

**Comment by gebner** [comment]
> I assume the same reservations as in #952 apply here?

Different reservations apply here.  #952 is about what arguments are sent to TC synthesis, while this issue is about how arguments are treated during TC synthesis.  These already behave quite differently.

- Everything is an `outParam` during TC synthesis.
- We don't commit to the first value of an `outParam`, we try them all.
- In arguments like `[A α] [B β]`, TC synthesis tries all instances of `A α`, and does not commit to the first one.  (Lean 4 only, afaict)

**Comment by leodemoura** [comment]
> I don't think we really depend on right-to-left solving otherwise. And the examples from that issues work in Lean 4.

Closing the issue. If it becomes an issue in the future, we can revisit this topic.
