### ISSUE TITLE
Naming convention for theorems

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#402]
We still don't have a solid naming convention for theorems. I think the current code base is using at least 3 different styles.

Work items:
- Design a naming convention for theorems.
- Make sure there is at least some support in the Lean community.
- Enforce the naming convention in this codebase.

We should this issue to discuss tradeoffs and problems.

**Comment by dselsam** [comment]
Here are three different naming styles in `src/Init`:

1. camelCase
  - `natAddZero`
  - `Classical.axiomOfChoice`
  - `Eq.mprProp`

2. snake case, using existing caps for components
  - `Lean.Simp.Ne_Eq`
  - `Lean.Simp.Or_True`
  - `Lean.Simp.or_true` (boolean version)

3. snake case, always using camelCase for components
  - `PUnit.eq_punit`
  - `runCatch_pure`
  - `seqLeft_eq_bind`

Notes:
  - A downside of (1) is that it may not be clear whether e.g. `Nat.isValidChar` returns `Bool` or `Prop`
  - A downside of (2) is that conjunctions and verbs read better lowercase, e.g. `Foo_and_Bar_iff_Rig` reads better than `Foo_And_Bar_Iff_Rig`
  - A downside of (3) is that it cannot distinguish between the `Prop`/`Bool` versions of e.g. `Or_True` vs `or_true`

Also:
  - The same conventions should probably apply to constructors and structure fields
  - Some automatically-generated constructions can sometimes only return `Prop`, e.g. `Or.recOn`

**Comment by leodemoura** [comment]
@dselsam Thanks for summarizing the different styles we have tried.
Your numbering reflects the order we have tried them.
We gave up on 1, and I think all devs and most users dislike it. 
We were also very unhappy with 2. 
Option 3 seems to be the most promising one. As you pointed out, it also has problems, but I can tolerate it.

**Comment by dselsam** [comment]
> Option 3 seems to be the most promising one. As you pointed out, it also has problems, but I can tolerate it.

I agree it is the best of the 3, and tentatively agree that it is good enough.

**Comment by tydeu** [comment]
I personally prefer option 2, but option 3 is fine as well. However, since the major problem with 2 is ugly verbs, I would suggest mixing 2 and 3. That is, I would preserve the original casing for nouns and use lower camelCase for verbs (i.e. `Foo_and_Bar_iff_Rig` instead of `foo_and_bar_iff_rig` and `PUnit.eq_PUnit` instead of `PUnit.eq_punit`). I would then have the namespace a given theorem is in dictate the meaning of verbs. That is, `Bool.or_true` means Bool `or`.

**Comment by Kha** [comment]
> > Option 3 seems to be the most promising one. As you pointed out, it also has problems, but I can tolerate it.
> 
> I agree it is the best of the 3, and tentatively agree that it is good enough.

I agree. Option 2 is intolerable to me because it does not abide by the rule that only values in `Sort` should be capitalized.

**Comment by dselsam** [comment]
I experimented with (3). It seems reasonable, and I pushed a not-quite-ready patch to https://github.com/dselsam/lean4/tree/names

Notes:
- It seems slightly awkward that we now have some `induction_on`s and some `inductionOn`s
- The patch required some staging care, since many theorems are used in Lean itself
- All tests pass
- I may have missed some `def`s, and I definitely missed both local variables and `tests` theorems
- Happy to do a more thorough pass if there is interest in merging

Related issues:
- We are still inconsistent about naming definitions that return propositions. For example, technically `isValidChar` should be `IsValidChar` since it returns a `Prop`, even though it is designed to be used as a `Bool` via `Decidable`.
- There has been some Zulip discussion (not represented yet in this issue) about sticking to camelCase for terms that return `Prop`, so e.g. `isValidChar`, `prime`, `primes`, and `and`. It is not directly related to this issue though, since the theorem names would stay the same.

**Comment by dselsam** [comment]
There seems to be consensus on (3). @digama0 recently proposed an alternative capitalization scheme for sorts which is compatible with (3) and which seems to have reached lean4-channel consensus on Zulip. The proposal is to only use PascalCase for terms that either (a) *syntactically* return `Sort <level != 0>` or (b) coerce to `Sort <level != 0>`. Many ideas were floated for how to deal with `Prop`-vs-`Bool` versions of `true` and `false`, and the simplest one is just to add two exceptions to the rule and capitalize `Prop` `True` and `False` as is currently done. Two of the benefits of this proposal are that (a) `Prop`s are often decidable and used in programming as `Bool`s and (b) it is easier to spot structure fields that will be erased at runtime. 

Examples:
```lean
def Set (α : Type u) : Type u := α → Prop -- PascalCase since it returns Type u 
def isValidChar : Char → Prop -- camelCase since it returns Prop

instance : CoeSort (Set α) (Type u) 
def ValidChars : Set Char -- PascalCase since Set Char coerces to sort

def SetNoCoe (α : Type u) : Type u := α → Prop 
def validCharsNoCoe : SetNoCoe Char
```

**Comment by leodemoura** [comment]
> Many ideas were floated for how to deal with Prop-vs-Bool versions of true and false, and the simplest one is just to add two exceptions to the rule and capitalize Prop True and False as is currently done. 

What about `Eq`, `And`, `Or`, `Iff`, `HEq`, etc?

**Comment by dselsam** [comment]
In @digama0's proposal, they would be lowercase, and their namespaces would be lowercase, but note that all five have notation and so would essentially never be used directly. Also, thanks to the notation, `and` and `or` would not clash with `Bool.and` and `Bool.or`.

**Comment by leodemoura** [comment]
> In @digama0's proposal, they would be lowercase, and their namespaces would be lowercase, but note that all five have notation and so would essentially never be used directly. Also, thanks to the notation, `and` and `or` would not clash with `Bool.and` and `Bool.or`.

Unfortunately, this is unacceptable to me. 

We should focus on the topic of this issue: naming convention for theorems. 
I am happy to hear feedback on how to name theorems. I am also willing to change the theorem names in the `Init` and `Std` packages. `Eq`, `And`, `Or`, etc are not theorems.

Regarding definitions such as
```lean
def isValidChar : Char → Prop -- camelCase since it returns Prop
```
We can avoid this problem by making them return `Bool`.

**Comment by FormallyVerifiedWaffleMaker** [comment]
> We gave up on 1, and I think all devs and most users dislike it.

Why is the camelCase style disliked? It seems quite elegant.

**Comment by tydeu** [comment]
@FormallyVerifiedWaffleMaker The problem was that since functions are in camelCase style it has to disambiguate a theorem about a function from a function itself (ex. `ofBoolUsingEqTrue` vs `ofBoolUsing_eq_true`).
