### ISSUE TITLE
Coercions again

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#403]
The Lean 4 coercions work much better than the Lean 3 ones, but they are still brittle and based on TC resolution.
"Bad" instances often trigger non-termination.
We can't support coercions from `A` to a subtype of `A` without allowing TC to invoke tactics, and we really don't want TC to invoke arbitrary tactics since it would make the system more complex, the caching mechanism will be less effective, and users will probably abuse the feature and create performance problems.
Finally, the TC rules are to strict and prevent us from finding a coercion for 
```lean
structure Foo (A : Sort _) := (foo : A)
structure Bar (A : Sort _) extends Foo A := (bar : A)
instance {A} : Coe (Bar A) (Foo A) := {coe := Bar.toFoo}
def getFoo {A} (F : Foo A) := F.foo
def bar : Bar Nat := {foo := 0, bar := 1}

#check getFoo bar -- fails because the expected type `Foo ?A` contains a metavariable.
```
One option is to write an extensible coercion resolution procedure.
Users would still be able to define (non-dependent) coercions using `instance`s, but the search and support for dependent coercions from `Prop` to `Bool` and `A` to subtype of  `A` would be handwritten.

**Comment by dselsam** [comment]
A quick comment while it is fresh. One complication compared to Lean3 is that `Coe` appears in instances that return other classes, such as:
```lean
instance [CoeHTCT α β] [Add β] : HAdd α β β where
  hAdd a b := Add.add a b
```
This means that we try to synth `Coe α β` a lot more behind the scenes, and also that we may try to synth `Coe α β` for arbitrary α and β.

**Comment by dselsam** [comment]
Related to the `getFoo` example above, here is a recent example from @kbuzzard that he and @patrickmassot both wish worked without needing the two `CoeFun` annotations in `trans`:
```lean
structure equiv (α : Sort u) (β : Sort v) :=
(to_fun    : α → β)
(inv_fun   : β → α)

infix:25 " ≃ " => equiv

namespace equiv

instance : CoeFun (α ≃ β) (λ _ => α → β) :=
⟨to_fun⟩

def symm (e : α ≃ β) : β ≃ α := ⟨e.inv_fun, e.to_fun⟩

def trans (e₁ : α ≃ β) (e₂ : β ≃ γ) : α ≃ γ :=
⟨e₂ ∘ (e₁ : _ → β), e₁.symm ∘ (e₂.symm : _ → β)⟩ -- without annotations, β would be an mvar

end equiv
```

**Comment by leodemoura** [comment]
@gebner Any thoughts about this issue? I am inclined to close this issue.

**Comment by gebner** [comment]
The most pressing coercion-related issue for mathport is https://github.com/leanprover-community/mathport/issues/94, which is due to the `hasOfNatOfCoe` instance.  The easiest fix here would be to remove `hasOfNatOfCoe` again (non-mathlib users could of course add it back, ideally *scoped* though).

> One option is to write an extensible coercion resolution procedure.

I don't think we need a rewrite of the coercion procedure at the moment.  We can keep our options open though by making sure the coercion classes don't leak anywhere else.  Concrete proposal: remove all abbrevs/defs from `Coe.lean` (to prevent accidental use) and replace the coercion notation by custom elaborators.  We already replace the `↑` notation in mathlib by an elaborator so that `↑t` and `(t : α)` elaborate to the same term.

**Comment by leodemoura** [comment]
@gebner Thanks for both suggestions. I have pushed both of them.
