### ISSUE TITLE
Make `String.Pos` opaque

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#410]
We should use the type system to avoid any confusion between byte and codepoint indices, e.g. by making `String.Pos` a structure containing a single `Nat`, though we also shouldn't introduce any need for "casting" where it wasn't necessary before. E.g. we probably want `0 : String.Pos` (and `(.+.) : String.Pos -> Nat -> String.Pos`?). And would this mean `String.bsize` should be a `String.Pos` as well?

**Comment by tydeu** [comment]
Here is something I think might be worth considering. Instead of manually creating opaque types like these with via a structure with a single arbitrarily named field, would it be wise to add some kind of special syntax in Lean for creating these types. That is, creating something like Haskell's `newtype`.

**Full disclosure**: I already created newtypes along these lines for my own project in Lean 4: https://github.com/tydeu/gaea/tree/master/Gaea/Newtype

**Comment by Kha** [comment]
There exist obviously beneficial field names like `byteIdx` or something in this case though

**Comment by tydeu** [comment]
@Kha That's fair, but that really wasn't my point.  My point is that opaque type wrappers are structures are distinct notions and that should be singled out in the syntax. Haskell does this and I think its wise. It also, at least in Haskell, provides other benefits. it permits easier automatic deriving of instance of the wrapper type from instances of the base type. It enables the creation of generic conversion to/from the newtype and between newtypes. Finally, I am not sure if this applies to Lean, but, in Haskell, it also allows the compiler to better optimize around it.
