### ISSUE TITLE
Bug with nested ifs and lets

### ISSUE THREAD

**Issue by fgdorais** [leanprover/lean4#4375]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

The following code gives `(kernel) declaration has free variables 'getHexDigit?'` on Lean 4.9.0-rc1.

```lean
def getHexDigit? (char : Char) : Option (Fin 16) :=
  if char.toNat < 0x0030 then
    none
  else
    let n := if char.toNat < 0xFF10 then char.toNat - 0x0030 else char.toNat - 0xFF10
    if h : n < 10 then
      some ⟨n, Nat.lt_trans h (by decide)⟩
    else if n >= 17 then
      let n := n - 7
      if h : n < 16 then
        some ⟨n, h⟩
      else if n >= 32 then
        let n := n - 32
        if h : n < 16 then
          some ⟨n, h⟩
        else
          none
      else
        none
    else
      none
```
Removing the second let or the third let eliminates the problem.

### Context

Discovered while updating [lean4-unicode-basic](https://github.com/fgdorais/lean4-unicode-basic) to v4.9.0-rc1. [Posted on Zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/v4.2E9.2E0-rc1.20discussion/near/443064939).

### Versions

`Lean (version 4.9.0-rc1, arm64-apple-darwin23.5.0, commit be6c4894e0a6, Release)`

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by llllvvuu** [comment]
Interestingly, when I minimized it to

```lean
example : Nat :=
  let n := 0
  if _ : True then
    let m := n
    if _ : m = 0 then
      let x := 0
      0
    else
      0
  else
    0
```

this is broken all the way back to Lean 4.0.0. It builds when changing the first line to `example (_ : Nat) : Nat :=`

The example provided by OP works on `nightly-2024-05-22` and is broken on `nightly-2024-05-23`.

**Comment by fgdorais** [comment]
Great insight! I thought let reassignments might be the issue but that was a red herring.

**Comment by hwatheod** [comment]
I also found a `(kernel) declaration has free variables` issue involving `let` which I minimized to the following:

```
example: Nat :=
  let a: Nat := 1
  have: a = 1 := by rfl
  let b: Nat := 2
  have: b = 2 := by rfl
  have: a = a := by rfl
  let c := 1
  0
```
It also fails at version 4.0.0. I thought it might be related to this issue so I am adding it here.

**Comment by llllvvuu** [comment]
> I also found a `(kernel) declaration has free variables` issue involving `let` which I minimized to the following:
> 
> ```
> example: Nat :=
>   let a: Nat := 1
>   have: a = 1 := by rfl
>   let b: Nat := 2
>   have: b = 2 := by rfl
>   have: a = a := by rfl
>   let c := 1
>   0
> ```
> 
> It also fails at version 4.0.0. I thought it might be related to this issue so I am adding it here.

Yup, same bug indeed; can remove all but the last `OfNat`

```lean
example: Nat :=
  let a: Nat := Nat.zero
  have: a = Nat.zero := rfl
  let b: Nat := Nat.zero
  have: a = b := rfl
  let c := 0
  Nat.zero
```

and then it gets assigned `let c : Nat := OfNat.ofNat.{0} Nat 0 ((let b : Nat := Nat.zero; fun (this : Eq.{1} Nat _uniq.4 b) => instOfNatNat 0) this)` as before, where `_uniq.4` should be `a`.

**Comment by kmill** [comment]
I do not think that this was fixed by #4110. The change in #4110 seems fine, but it does not fix the underlying issue in (I think!) `isDefEq`.

Here's another test case that's simpler still:
```lean
example :=
  let a : Nat := Nat.zero
  fun (_ : True) =>
  let b : Nat := Nat.zero
  (fun (_ : a = b) => 0)
```
While #4110 makes some ill-formed metavariable assignments end up not mattering, they are still present. The issue seems to be that the OfNat instance metavariable for `0` forgets to include `a` as one of the let bindings it depends on.

If you add well-formedness checks to `checkTypesAndAssign` like so, then you can see this reflected as an elaboration error, as "typeclass instance problem is stuck".
```lean
private def checkTypesAndAssign (mvar : Expr) (v : Expr) : MetaM Bool :=
  withTraceNodeBefore `Meta.isDefEq.assign.checkTypes (return m!"({mvar} : {← inferType mvar}) := ({v} : {← inferType v})") do
    if !mvar.isMVar then
      trace[Meta.isDefEq.assign.checkTypes] "metavariable expected"
      return false
    else
      -- must check whether types are definitionally equal or not, before assigning and returning true
      let mvarType ← inferType mvar
      let vType ← inferType v
      if (← withTransparency TransparencyMode.default <| Meta.isExprDefEqAux mvarType vType) then
        unless (← MetavarContext.isWellFormed (← mvar.mvarId!.getDecl).lctx v) do
          throwError "in checkTypesAndAssign: metavariable has incompatible local context for value\n{indentD v}\nMetavariable:{indentD mvar.mvarId!}"
        unless (← MetavarContext.isWellFormed (← mvar.mvarId!.getDecl).lctx vType) do
          throwError "in checkTypesAndAssign: metavariable has incompatible local context for type\n{indentD v}\nMetavariable:{indentD mvar.mvarId!}"
        mvar.mvarId!.assign v
        pure true
      else
        pure false
```

Is there any justification in the PR for not zeta reducing being a bug [in this comment](https://github.com/leanprover/lean4/pull/4410/files#diff-5436b30907918d5d8e2cedc84a326932fb8549ecb01677c117f1fb77b42283f2R567-R570)? If not, I think a followup fix should change that comment.

**Comment by llllvvuu** [comment]
I had a similar theory prior to changing the fix:

https://github.com/leanprover/lean4/commit/625b45ce47fe033e6d5131cfdb8be0c25ba8ba62 (this implementation is not good but the idea was essentially that this code doesn't loop through all let decls:

https://github.com/leanprover/lean4/blob/93fa9c8837e071a866b62e2ca73c22a362ccb988/src/Lean/Meta/ExprDefEq.lean#L390-L419

I backtracked on that idea because it wasn't clear to me that leaving in those fvars was indeed unintentional.

**Comment by Kha** [comment]
@kmill Your test case is failing for me on "Mathlib stable" but not latest or nightly

**Comment by Kha** [comment]
Closing until reconfirmation
