### ISSUE TITLE
Admit incomplete theorems

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#440]
```
theorem t1 : True := _
theorem t2 : True := t1  -- unknown identifier 't1'
```
This would simplify incrementally working on multiple theorems in parallel

**Comment by kbuzzard** [comment]
I have noticed you prefer this style in the exercises for your course, which are full of errors caused by it. Why not just `sorry` the proofs? When I am writing Lean code I really don't like to have any errors at all, I plug all holes with sorry/admit, because I worry that one typo which causes an error 5 lines up will not be noticed if I allow errors everywhere.

**Comment by Kha** [comment]
I don't think this is directly related to the course exercises because there we have mostly independent theorems (for now). The thinking there was to say "Your solution is complete if all errors are gone". That could be trivially extended to "...and 'sorry' warnings", of course.

**Comment by Kha** [comment]
IOW, I meant to use `_` above as a placeholder for a more complex incomplete proof, not as an representative example
