### ISSUE TITLE
option to downgrade unused termination hint error to a warning

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#4804]
When using `set_option debug.byAsSorry`, some results become non-recursive and so the termination hints become errors.

Could we have another debug option for use in conjunction with `byAsSorry` which turns these errors into warnings?

**Comment by nomeata** [comment]
To avoid a proliferation of options, how about always making them warnings (after all, the code still works to some extent, but maybe not as intended)? Or make them warnings if the `byAsSorry` is enabled?

Although I'm having doubts about that option anyways if there is the expectation that everything will work as before. For example functional induction principles will certainly fail or look different, as do equational theorems. So some breakage is unavailable? (Or maybe you are only hitting this with recursive theorems, where we don't have or need these features)

Maybe `byAsSorry` could be less aggressive, like it already tries to avoid worrying `data`? Too bad that recursion isn't easily recognizable in advance, so maybe not.

**Comment by digama0** [comment]
I don't think this should be an option, unused whatever should not be an error in the first place.

**Comment by nomeata** [comment]
Agreed, making this way warning is the easiest way out here.

(I do wonder when we want errors and when warnings. Do we have a written guideline somewhere?)

**Comment by semorrison** [comment]
Yes, let's downgrade this error to a warning!

**Comment by digama0** [comment]
> (I do wonder when we want errors and when warnings. Do we have a written guideline somewhere?)

The guideline I use is that an error should be something on the critical path to interpreting the meaning of the input, or when something is incorrect (i.e. does not have meaning in the type system). When something can be interpreted but is not what the user probably wanted, that is a warning, although you may even use a "red colored linter error" to display it. (Example: overflowing literal in a fixed width type.) The point is that these are things the user has the option to say "I don't care, do it anyway", while hard errors are for things where there is no possibility of ignoring the failure and the meaning of subsequent code is seriously compromised.

**Comment by nomeata** [comment]
That sounds roughly what I expected, although the devil is in the details; “hard errors are for things where there is no possibility of ignoring the failure and the meaning of subsequent code is seriously compromised.” could mean that `rw [doesnotexist]` could be a warning (it’s possible to ignore it and subsequent code is not seriously compromised) or – a bit tongue in cheek – basically any kind of failure that can be turned into a sorry.

OTOH, ignoring a `termination_by` does affect subsequent code – if that is expecting certain `.eq_<n>` or `.induct` lemmas only generated for recursive functions.

That’s probably not what you meant and I agree that that former should be an error and the latter can be a warning; just saying that I find it hard to give a really precise specification.

**Comment by nomeata** [comment]
Here is another attempt:

 * Info: The user explicitly asked for output (`#check`, `simp?`, `termination_by?`).

 * Warning: The code mostly unambiguous, it’s low risk that it isn’t doing what the user intended, but also clearly not great style or otherwise clearly not “done” yet. There is a clear action to fix it, and (likely) an option one can set to disable it (using `sorry`, unused variables, using deprecated things).
 
   Linters would fall in the same category, and differ only by their implementation (external, post-hoc, rather than internal to some logic).
   
 * Error: the code as written clearly cannot be interpreted the way the user intended. Still lean does as much as it can with it (ignoring a command, declaring a definition as `parital` if the body doesn’t work, using error-to-sorry, ignoring an unusable entry in a `rw […]` or `simp […]` sequence, ignoring a termination annotation on a recursive functions.)
 
By this categorization, using `logError` (not `throwError`!) on termination annotations on non-recursive functions is correct (as clearly the user expected them to be recursive), I’d say.

This doesn’t help Kim with `debug.byAsSorry` so pragmatically it’s ok to demote them to a warning. But I’d say that’s really a deficiency of the (still new) `debug.byAsSorry` feature, that it breaks more than ideally it would.

(All not super important.)

**Comment by digama0** [comment]
> That sounds roughly what I expected, although the devil is in the details; “hard errors are for things where there is no possibility of ignoring the failure and the meaning of subsequent code is seriously compromised.” could mean that `rw [doesnotexist]` could be a warning (it’s possible to ignore it and subsequent code is not seriously compromised) or – a bit tongue in cheek – basically any kind of failure that can be turned into a sorry.

It is possible to ignore it, yes, but that is not following the intent of the code, which is to rewrite with `doesnotexist`. When the compiler unilaterally changes the meaning of the program away from what the user asked for, (because they asked for something that is nonsensical or impossible), that's an error condition. Of course an error does not mean you should halt compilation - a robust compiler should always keep going so as to produce as many (independent) errors as possible.

> OTOH, ignoring a termination_by does affect subsequent code – if that is expecting certain .eq_<n> or .induct lemmas only generated for recursive functions.

I didn't say anything about "affecting subsequent code", because in lean literally anything can "affect subsequent code", it's not a very good differentiator. Rather I talked the intent and meaning of the code that was given. Lean code is not explicit about whether eq_<n> or .induct lemmas are generated, so there is nothing to really key on here. You might consider that a lean design issue, but it is what it is, user intent regarding the existence or indexing of autogenerated lemmas is difficult to establish based on the text itself. Especially considering that the lean devs explicitly retain the flexibility to make changes to the generation of these lemmas at any time I would say that it's not really possible for the user to give their intent on such matters, because lean isn't listening and doesn't want to hear it anyway. If there actually was such an annotation, like `@[generate_this foo.eq_1]` in the code, you could use this to give an error if the definition was not made.
