### ISSUE TITLE
Discriminant refinement doesn't like anonymous constructors anymore

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#482]
The following code fails since https://github.com/leanprover/lean4/commit/73797841baa66d9f8c5c2b851ba331b8137a9d51:
```
inductive Mem' (a : α) : List α → Prop where
  | intro (as bs) : Mem' a (as ++ (a :: bs))

example {x : α} (h : Mem' x l) : True :=
  match h with
  | ⟨as', bs'⟩ => True.intro
```
It does work with the named constructor

**Comment by leodemoura** [comment]
@Kha The new refinement algorithm that we discussed yesterday requires the type of the problematic pattern. To get the type, we need to elaborate the pattern. Some patterns cannot be elaborated when we provide the expected type because it would trigger the type mismatch error we are trying to fix in the first place. Thus, the new refinement algorithm is elaborating the problematic patterns without the expected type, and it consequently cannot handle anonymous constructors. I was assuming this was a minor limitation. 
I will get the new refinement algorithm working before I try to fix this. 
A possible fix is to replace all indices in the expected type with fresh metavariables to make sure we will not get a type mismatch. In the example above, the expected type would become `Mem' ?m1 ?m2` instead of `Mem' x l`.

**Comment by Kha** [comment]
> A possible fix is to replace all indices in the expected type with fresh metavariables to make sure we will not get a type mismatch. In the example above, the expected type would become `Mem' x ?m` instead of `Mem' x l`.

Nice, makes sense!
