### ISSUE TITLE
Formatter/Parenthesizer errors for non-builtin syntax categories

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean4#485]
```lean
import Lean
open Lean Lean.Parser
declare_syntax_cat foo

@[fooParser] def hole := leading_parser "_"
@[fooParser] def num  := checkPrec maxPrec >> numLit 
-- error: invalid [formatter] argument, unknown syntax kind 'num'
```
The relevant lines are:
https://github.com/leanprover/lean4/blob/master/src/Lean/PrettyPrinter/Formatter.lean#L66 
https://github.com/leanprover/lean4/blob/master/src/Lean/PrettyPrinter/Parenthesizer.lean#L127 

I baselessly suspect a logic bug in those two lines for the non-builtin case. It seems to work when I remove the `builtin &&`.

**Comment by Kha** [comment]
Registered parsers should always have an outer `leading/trailing_parser`, otherwise there is no syntax kind to attach a macro/elaborator to. Note that the higher-level `syntax` does this automatically.

**Comment by Kha** [comment]
Using the literal parser directly without an outer syntax kind is kind of a hack we introduced at some point so that quotations don't have to worry about the difference between "an `ident`" and "a `Lean.Parser.Term.ident`". But I would suggest to wrap them with `leading_parser` for now, *especially* if you do want to attach different meaning to them (e.g. a more lenient name lookup on `Term3.ident` that unfolds to the correctly cased Lean 4 `ident`).

**Comment by dselsam** [comment]
Got it, thanks!
