### ISSUE TITLE
`def _root_...` creates literal `_root_` namespace

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#490]
```lean
namespace Foo
def _root_.bar := 1
end Foo
#check bar
#check Foo._root_.bar
```

**Expected behavior:** for the first `#check` to work

**Actual behavior:** the second `#check` unexpectedly works

**Comment by leodemoura** [comment]
We should not create a `_root_` namespace, and this part is a bug and should be fixed.
This issue also proposes a new feature, the ability to add a declaration to the "root" namespace without closing the current one. I view this feature as a low priority and don't want to think about it right now. For example, what can this feature break? Do we have to change how we process attributes?

**Comment by Kha** [comment]
Yeah, not accepting the second check is good enough for now

**Comment by leodemoura** [comment]
@gebner Is this feature important for the mathlib port?

**Comment by digama0** [comment]
Yes, this feature was implemented in lean 3 and gets some use. It's not incredibly common but there isn't any obvious way for synport to drop in an alternative without significantly changing the surrounding syntax (closing all the namespaces, adding the definition, reopening the namespace and adding all the variables and local things back...)

**Comment by gebner** [comment]
> It's not incredibly common

To give concrete numbers, it occurs 651 times in mathlib.

We might also need it to override instance names in the port: https://github.com/leanprover-community/mathport/issues/106

**Comment by digama0** [comment]
These are to some extent unexplored questions since the way lean 4 handles namespaced definitions, as though there was a `namespace Foo` around the definition, is new.

Here's a way that I thinnk can lead to coherent answers to these questions: Imagine that we can write `namespace _root_` which acts just like a regular namespace (it is still nesting "inside" `namespace Foo` and would be closed with `end _root_`), where the only difference from a regular namespace is that instead of definitions getting the name `Foo._root_.y` the `*._root_` part is removed.

With that model, the name resolution would act as though the `open` and `export`s are still in scope, but root-scoped definitions and `Bar` scoped definitions (in the `def _root_.Bar.y` case) would take precedence. In your example, `x` would refer to `Foo.x` and `z` would refer to `Bla.z` like you said.

The behavior of `@[scoped attr]` should be the same as for `@[scoped attr]` on a `def Bar.foo`. I had to check lean to see what it does, and it looks like it makes the attribute active in the namespace `Foo`, not `Bar`. Consistency would then suggest to make `@[scoped attr]` scope the attribute in the namespace `Foo` (and the current section) even if the definition itself is at `_root_.y`.
