### ISSUE TITLE
Server gets out of sync after inserting space at end of comment

### ISSUE THREAD

**Issue by gebner** [leanprover/lean4#549]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Steps to Reproduce

```lean
import Lean

open Lean Elab Command

syntax (name := exportPrivate) "export" "private" : command

/--
`export private a b c in foo bar`
-/ -- insert space between - and / here and delete it again
@[commandElab exportPrivate] def elabExportPrivate : CommandElab
| _ => throwUnsupportedSyntax
```

The file above compiles without error.  If you insert a space between between `-` and `/` at the end of the comment, then Lean produces the error `expected 'abbrev', [...]`.  However, this error remains even after you remove the space again.

I would expect the error to go away after deleting the space.

### Versions

Nightly from June 29.

**Comment by Vtec234** [comment]
This happens because we assume a change cannot merge two or more previous commands into one. I guess Lean is now officially a [crazy grammar](https://github.com/leanprover/lean4/blob/d55c069172537554dfa396d5bceab1bc39c80e43/src/Lean/Server/FileWorker.lean#L231) :) In fact, one can produce arbitrarily-long counterexamples to this like so:
```lean
/--
def a1 := sorry
def a2 := sorry
def a3 := sorry
...
- / -- remove space here
```

I suppose we could re-parse the entire file on each edit, but perhaps docstrings should behave like normal comments and not produce commands when unterminated.

**Comment by Vtec234** [comment]
The command that gets produced out of an unterminated `/--` is, of all things, a [`class abbrev`](https://github.com/leanprover/lean4/blob/d55c069172537554dfa396d5bceab1bc39c80e43/src/Init/NotationExtra.lean#L142). Maybe that is the real bug?

**Comment by tydeu** [comment]
@Vtec234 That may simply be because `class abbrev` is the only non-built-in core syntax (i.e., not a `declaration`) that has a leading `declModifiers` (of which block comments area part of). This makes it the first result for such parsers (and thus the thing the parser tries to turn the syntax into).
