### ISSUE TITLE
Unable to figure the term when destructing an inductive proposition

### ISSUE THREAD

**Issue by fduxiao** [leanprover/lean4#5700]
I defined a simple type and a simple relation.
```lean
inductive Three: Type where
  | a | b | c

inductive Rel3: Three -> Three -> Prop where
  | ab: Rel3 a b
  | cb: Rel3 c b
```

`Rel3` is obviously transitive.
```lean
theorem rel3_trans: forall {x y z: Three}, Rel3 x y -> Rel3 y z -> Rel3 x z := sorry
```

I tried to prove it. But `lean` failed to figure out the correct term if you destruct some of type `Rel3 x y`
```lean
theorem rel3_trans: forall {x y z: Three}, Rel3 x y -> Rel3 y z -> Rel3 x z := by
  intros x y z Hxy Hyz
  cases Hxy
  case ab =>
    -- Here in case ab, Hyz should be `Rel3 b z`, but lean sticked to `Rel3 y z`.
    -- And, you are unable to destruct `Hyz` again by `cases Hyz`
    admit
  case cb =>
    admit
```

If you use `cases Hyz` in the above, `lean` will complain that `tactic 'induction' failed, major premise type is not an inductive type`.

Meanwhile, you can prove this in Coq.
```coq
Inductive Three :=
  | a | b | c.

Inductive Rel3: Three -> Three -> Prop :=
  | ab: Rel3 a b
  | cb: Rel3 c b.


Theorem rel3_trans: forall x y z: Three, Rel3 x y -> Rel3 y z -> Rel3 x z.
Proof.
  intros x y z Hxz Hyz.
  destruct Hxz.
  - destruct Hyz.
    + apply ab.
    + apply ab.
  - destruct Hyz.
    + apply cb.
    + apply cb.
Qed.
```

Am I using the correct strategy to prove that? In `lean`, how do you prove it?

**Comment by fduxiao** [comment]
What about this one even simpler?
```lean
inductive T: Type where
  | a | b

inductive R: T -> T -> Prop where
  | r: R a b

example: Not (R b a) := by
  intros H
  cases H
  admit
```

**Comment by digama0** [comment]
Questions of this nature are better suited for the [Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4), please use issues on this repo only to report actual issues in lean.

The error in your code is that `a` and `b` in `R` are being interpreted as variables, not elements of `Three`, because they are namespaced as `Three.a` and `Three.b`, so you can either write that or use `.a` and `.b` in the definition of `Rel3`. If you would like to avoid the implicit introduction of `a` and `b` as variables, you should use `set_option autoImplicit true` or add it as a global setting in the lakefile.

```lean
inductive Three: Type where
  | a | b | c

inductive Rel3: Three -> Three -> Prop where
  | ab: Rel3 .a .b
  | cb: Rel3 .c .b

theorem rel3_trans: forall {x y z: Three}, Rel3 x y -> Rel3 y z -> Rel3 x z := by
  intros x y z Hxy Hyz
  cases Hxy <;> cases Hyz
```
