### ISSUE TITLE
Regression after refactoring `Nat.le`

### ISSUE THREAD

**Issue by fgdorais** [leanprover/lean4#644]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

There has been a small regression after changing the definition of `Nat.le` to an inductive proposition in commit [7066619](https://github.com/leanprover/lean4/commit/70666191232a8832e26ed32bb4b0734c54aac4c2). Before the change, this code worked:
```lean
def Bool.ofFin2 : Fin 2 → Bool
| ⟨0,_⟩ => false
| ⟨1,_⟩ => true
```
Now this reports `error: missing cases: (Fin.mk (Nat.succ (Nat.succ _)) _)`, which is easily fixed by adding a third case but it was nice to not have to point out explicitly that n+2 is never less than 2. I hope the old behavior can be recovered somehow.

### Versions

Original behavior happens with `nightly-2021-08-21` and new behavior happens with `nightly-2021-08-22`.

**Comment by fgdorais** [comment]
I found the [Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Nat.2Ele.20backport) that led to this change for `Nat.le`. It looks like the change might have fixed more than it broke.

**Comment by leodemoura** [comment]
Yes, this regression is due to the `Nat.le` change.
The dependent pattern matching compiler is based on the tactic `cases`, `subst`, and `intro`. It does not try "hard" to show an inductive datatype is empty. In your example, the missing case contains the hypothesis `h : succ (succ x) < 2`.  Before the change, this was equivalent to `h : (Nat.ble (succ (succ (succ x))) 2) = true`, which reduces to `h : false = true`, and the tactic `cases h` discharges this case. After the change, the hypothesis `h` is equivalent to `h : Nat.le (succ (succ (succ x))) 2`, where `Nat.le` is an inductive predicate. The tactic `cases h` produces a new subgoal containing `h' : Nat.le (succ (succ (succ x))) 1`. So, to close the branch we would have to apply `cases` 3 times.
Note that, this example also fails in Lean 3 where `Nat.le` is defined using the same inductive datatype.

I am pushing a change where we use the `contradiction` tactic to close missing (and contradictory) branches. It tries hard and can handle the example above. However, it also has limitations and will fail for more complex examples. In the future, I will allow users to select the tactic used to close the missing branches.
