### ISSUE TITLE
Multiple constants in one line

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#645]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

why can I write `α β γ : Type` when abstracting over Types, as in:
```
#check fun (α β γ : Type) (g : β → γ) (f : α → β) (x : α) => g (f x)
```

but I cannot write:

```
constant α β γ : Type
```

### Steps to Reproduce

The above constant returns error:

```
failed to infer binder type
when the resulting type of a declaration is explicitly provided, all holes (e.g., `_`) 
in the header are resolved before the declaration body is processed
```

It seems I have to write the more verbose:

```
constant α : Type
constant β : Type
constant γ : Type
```

### Versions

Lean (version 4.0.0-nightly-2021-08-25, commit 63b11368cab0, Release)

**Comment by leodemoura** [comment]
The error message was improved.
I believe we don't need to declare multiple constants in a single line. So, I am closing this issue.

That being said, the keyword `constant` may be a misleading name since it is actually an opaque definition in Lean 4.
I updated the "Theorem Proving in Lean 4" document, and it does not mention the `constant` keyword in the first chapter anymore.
