### ISSUE TITLE
Improving `pp.analyze`

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#651]
`set_option pp.analyze true` is great for generating terms that can be re-elaborated.
However, it often generates confusing output, and I have to turn it off. 

Here is a small example:
```lean
example {n} (as : { x : List Nat // x.length = n }) : as.val.length = n := by
  cases as
  done
```
The output is
```lean
n : Nat
val✝ : List Nat
property✝ : List.length val✝ = n
⊢ List.length (Subtype.mk (p := fun x => List.length x = n) val✝ property✝).val = n
```

With `set_option pp.analyze false`, I get

```lean
n : Nat
val✝ : List Nat
property✝ : List.length val✝ = n
⊢ List.length { val := val✝, property := property✝ }.val = n
```

**Comment by leodemoura** [comment]
Another weird example occurring in a goal
```lean
...
h :  Eq (α := List Nat) (List.reverse []) []
⊢ 
...
```

**Comment by leodemoura** [comment]
Here is another example
```lean
example (x y : Nat) : x + 1 = y + 1 := by
  apply congr
  done
```
We get the output
```|
Goals (2)
case h₁
x y : Nat
⊢ Eq (α := Nat → Nat) (HAdd.hAdd x) (HAdd.hAdd y)

case h₂
x y : Nat
⊢ 1 = 1
```
The problem is that `pp.analyze` is trying to ensure that the terms can be re-elaborated. So, it makes sense it generates `Eq (α := Nat → Nat) (HAdd.hAdd x) (HAdd.hAdd y)`. However, we on the goal view and error messages, being able to re-elaborate terms is not essential when it affects readability. Moreover, the widgets feature will allow us to explore terms interactively. We may even have an option on the interface where we ask for a term that can be re-elaborated.
Thus, I think we should set `pp.analyze = false` by default, and turn it on for applications where it is essential (e.g., mathport).

**Comment by leodemoura** [comment]
```lean
#check @funext
-- funext : ∀ {α : Sort u_1} {β : α → Sort u_2} {f₁ f₂ : (x : α) → β x}, (∀ (x : α), f₁ x = f₂ _) → Eq.{imax u_1 u_2} f₁ f₂

set_option pp.analyze false
#check @funext
-- funext : ∀ {α : Sort u_1} {β : α → Sort u_2} {f₁ f₂ : (x : α) → β x}, (∀ (x : α), f₁ x = f₂ x) → f₁ = f₂
```

The output produced by `pp.analyze true` is correct, but
-  The `f₂ _` is correct, but I guess it obfuscates. 
- `Eq.{imax u_1 u_2} f₁ f₂` is including unnecessary universe information.

**Comment by fgdorais** [comment]
Is it possible to temporarily have `pp.analyze` set to false by default until it becomes more useful. It's been a pain to remember to turn it off whenever I start editing a file. Also, turning it off seems to improve performance quite a bit right now.

**Comment by leodemoura** [comment]
@fgdorais I disabled it for now.

**Comment by dselsam** [comment]
Leo's examples fall into three categories: 

- (a) missing heuristics in `pp.analyze` that would allow more concise terms that still roundtrip (e.g. `Eq.{imax u_1 u_2}`)
- (b) terms where roundtripping is not desired (e.g. `Eq (α := List Nat) (List.reverse []) []`)
- (c) sound heuristics in `pp.analyze` that are undesirably concise (e.g. `f₁ x = f₂ _`)

I have so far personally found `pp.analyze`/roundtripping to be a great heuristic for displaying error messages, since I have found that when `pp.analyze` needs to add more information to ensure roundtripping, this missing information is often relevant to the error at hand. The performance overhead of `pp.analyze` is also unlikely to be a problem for printing error messages.

On the other hand, based on Leo's (b) examples, it seems like `pp.analyze` might *not* be a default-worthy heuristic for regular tactic state pretty-printing (even when ignoring the performance considerations). @leodemoura in light of your (b) examples, can you think of any examples where you actually do want a tactic state to be pretty-printed by default with more information than the original default settings would use? If not, then obviously `pp.analyze` should not be used by default to pretty-print tactic states.

Note: some of `pp.analyze` has already made it into the built-in delaborators, specifically the name un-resolution of https://github.com/leanprover/lean4/commit/b36baa143faee0b016b190913c6c176b352bde2f. If we want the old status-quo for default pretty-printing tactic states, then this change would need to be guarded by `pp.analyze` and the old weaker un-resolution code restored for the default code path.

**Comment by leodemoura** [comment]
> can you think of any examples where you actually do want a tactic state to be pretty-printed by default with more information than the original default settings would use? If not, then obviously pp.analyze should not be used by default to pretty-print tactic states.

@dselsam We are going to have widgets very soon in Lean 4, and users will be able to interactively explore expressions (e.g., visualize implicit arguments) in error messages, traces, and tactic states. So, `pp.analyze := true`  by default is not crucial for these use cases. 

We should set `pp.analyze := true` only in use cases where roundtripping is important (e.g., mathport). We should also `pp.analyze := true` in the `#print` command.

I think fixing (a) and (c) is important for mathport and `#print`. I have used `#print` for debugging automatically generated constructions, and problems (a) and (c) also occur in this scenario.

**Comment by dselsam** [comment]
I will address both (a) and (c). Any thoughts on a more appropriate heuristic for when an easily-inferred term should (and should not) be replaced with `_`? What about by size, i.e. only use `_` if the original syntax would have had more than (say) 5 nodes?

**Comment by leodemoura** [comment]
> Any thoughts on a more appropriate heuristic for when an easily-inferred term should (and should not) be replaced with _? What about by size, i.e. only use _ if the original syntax would have had more than (say) 5 nodes?

I think we should not perform this kind of replacement.  
I did not find this kind of replacement useful when I was inspecting automatically generated definitions/theorems.

**Comment by leodemoura** [comment]
I am closing this issue since `pp.analyze` is not set to true by default anymore.
