### ISSUE TITLE
Help synthesize Prop and boolean expressions

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#764]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

It is surprising that something that looks so simple doesn't work.  I think folks from other
programming languages would be very surprised by this, can we fix it?

```lean
#eval (5 > 2) == true
```

Similarly this also fails:

```lean
#eval (5 > 2) = true
```

saying
```
failed to synthesize
  Decidable ((5 > 2) = (true = true))
```

### Steps to Reproduce

see above

**Expected behavior:** [What you expect to happen]

```
true
```

**Actual behavior:** [What actually happens]

```
failed to synthesize instance
  BEq Prop
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by tydeu** [comment]
@lovettchris 

> ```
> #eval (5 > 2) == true
> ```

This does not work because Lean is inferring `Prop` for both sides (as the `5 < 2 : Prop` comes first) and there is not (and theoretically cannot be) a `BEq` instance for  `Prop`. However, the inverse, `#eval true == (5 < 2) `, works fine (as Lean then infers `Bool` for both sides which solves the problem).

> ```
> #eval (5 > 2) = true
> ```


This one fails because Lean also lacks `Decidable` instance for `Prop` equality. As before, the inverse `#eval true = (5 > 2)` works. Here, though, such an instance could be made like so:

```lean
instance [d : Decidable (p ↔ q)] : Decidable (p = q) :=
  match d with
  | isTrue h => isTrue (propext h)
  | isFalse h => isFalse fun heq => h (heq ▸ Iff.rfl)

#eval (5 > 2) = true -- now produces `true` as desired
```

However, I suspect such an instance is missing because it has to rely on `propext`, which is an axiom.

**Comment by lovettchris** [comment]
thanks for the explanation, obviously I still have a lot to learn, but from what I've seen so far, I worry when a language has made itself so powerful that the simple things turn out being very complicated, and in some cases not even possible.  Perhaps Lean needs to strive a little harder to make the simple things simple and the complex things possible.  Right now it seems Lean is making the complex thing simple at the cost of some simple things are impossible.  This right balance takes true genius to discover sometimes...

**Comment by tydeu** [comment]
@lovettchris the key Lean oddity here is simply that `<`/`>` and `<=`/`>=` are propositional operations, not Boolean operations in Lean. 

It is important to remember that while Lean is aiming to eventually become a general-purpose language, the theorem proving aspect is still key. Thus, it is more designed for people with a functional programming, mathematical logic, and/or type theory background who also want to do general-programming rather than the other way around (at least at the moment).  In essence, Lean's current design is to attract exactly the kind of people who want certain conventionally complex things made simple even at the cost of potentially make some simple things more complex.

However, a lot of this is just due to the fact that having an easy onboarding for the general-purpose side (with a rich stdlib and clean errors, etc.) is not the priority right now. Currently, afaik, the main priority is to get Lean in shape for Mathport (as mathlib is the core of Lean's current userbase) and develop the components necessary (not just desirable) for CS applications. Thus, many things (like this) which could be made more convenient, but is still currently serviceable, don't end up the focus.

Also, having a few oddities here and there is quite common for a programming language. For example in Python `0 == False` and `isinstance(False, int)` which makes it very difficult to properly distinguish between `False` and `0` in a program whereas it is much easier to do so in many other OO interpreted languages (e.g., JS, Ruby, etc.).

**Comment by tydeu** [comment]
also, I am surprised I hadn't thought to ask of this until now, but @lovettchris what is the use case for this? In some ways the fact that `#eval x == true`/`#eval x = true` does not work is actually a blessing in disguise, as comparing a Boolean-like value to `true` is almost always an error / bad code smell (e.g., the kind of thing linters would yell at you for).

**Comment by leodemoura** [comment]
> However, I suspect such an instance is missing because it has to rely on propext, which is an axiom. 

@tydeu This is an oversight. We should add this instance. Thanks for catching the problem. Could you please submit a PR for it?

For the `#eval (5 > 2) == true`, we can write a custom elaborator for it that does something special for the `Prop` case. I think the `Prop` vs `Bool` issue is an obstacle for many new users. The custom elaborator is a bit ad-hoc, but I think it is defensible for this recurrent issue.
Note that, the `==` notation already uses the special `binrel%` auxiliary elaborator that makes sure that examples such as
```lean
variable (x : Nat) (y : Int)

#check x == y      
#check y == x      
```
work.

**Comment by tydeu** [comment]
@leodemoura 

> @tydeu This is an oversight. We should add this instance. Thanks for catching the problem. Could you please submit a PR for it?

certainly, will do
