### ISSUE TITLE
Trace messages missing in Emacs

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#977]
```
[Meta.isDefEq] (trace hidden)
  [Meta.isDefEq] (trace hidden)
```
is not terribly helpful. We should show the full trace as before if there is no interactive support.

**Comment by Kha** [comment]
@Vtec234 Any idea on how to fix this? Should we simply check whether there are any `rpcSessions` when publishing diagnostics, or are there edge cases in there?

**Comment by Vtec234** [comment]
The principled solution is most likely to add a `hasInfoview` field to the initial LSP configuration message and have vsc add that set to `true`, otherwise assume it is `false` (so no need to modify lean4-mode.el). I can look into implementing this later today.

**Comment by gebner** [comment]
> The principled solution is most likely to add a hasInfoview field to the initial LSP configuration message

I agree, such a field is the best option.  (The name `hasInfoview` might be misleading though, there's an "info view" in the emacs mode, and we've had a text-only infoview in vscode.  I would paint the bikeshed `hasWidgets` or `hasInteractiveDiagnostics`.)

> I can look into implementing this later today.

Please give me a heads-up so that we can add this flag to lean.nvim as well.
