### ISSUE TITLE
ST.Ref/IO.Ref cannot be Inhabited

### ISSUE THREAD

**Issue by JLimperg** [leanprover/lean4#984]
With the refactor in e3241e82bce83048accbbb2eac3f281a7e74b5d7, it seems like it has become impossible to have `Inhabited (ST.Ref σ α)`, even with `Inhabited α`. This makes it much harder to work with references (or data structures containing references), since e.g. many array functions become unusable. Any chance this capability could be restored?

(Maybe the more fundamental question is whether `ST.mkRef` needs to be monadic. It's not really a side-effecting operation, but it's monadic in Haskell as well, so there's probably a good reason.)

**Comment by Kha** [comment]
> Maybe the more fundamental question is whether `ST.mkRef` needs to be monadic. It's not really a side-effecting operation

`mkRef` does not respect referential transparency.
```
  let r ← IO.mkRef 0
  r.modify (· + 1)
  r.modify (· + 1)
```
is not the same thing as
```
  let r ← IO.mkRef 0
  r.modify (· + 1)
  let r ← IO.mkRef 0
  r.modify (· + 1)
```

**Comment by gebner** [comment]
It was an intentional decision to make these type non-inhabited.

> Not having an Inhabited instance for `IO.Ref` and structures containing `IO.Ref` is certainly the right thing in my eyes. Creating a reference is a side-effecting operation. And it would be very surprising if the default value contained a globally shared reference.

That is, `(default : Inhabited (IO.Ref Nat))` would be global mutable state.

**Comment by gebner** [comment]
I assume that you're asking this questions because you're trying to port aesop to the current Lean nightly, and you're having troubles with this [`GoalData` structure](https://github.com/JLimperg/aesop/blob/c682301c1470559b8801e4f4a56c27a4cf2f2bd3/Aesop/Tree.lean#L223):
```lean
structure GoalData (Goal Rapp : Type) : Type where
  id : GoalId
  parent? : Option (IO.Ref Rapp)
  children : Array (IO.Ref Rapp)
  goal : MVarId
  unificationGoals : HashSet MVarId
  successProbability : Percent
  -- ...
  deriving Inhabited
```

My general advice would be to avoid circular references (`parent?`) and nested references.  Instead I would use an arena approach for the tree, allocate the nodes in an array (or hashmap depending on sparsity), and use indices for parents and children (i.e., `parent? : Option Nat` and `children : Array Nat`).  Then you don't need to worry about memory leaks either.

**Comment by JLimperg** [comment]
> mkRef does not respect referential transparency.

Fair. Maybe not the smartest question I've ever asked.

> That is, (default : Inhabited (IO.Ref Nat)) would be global mutable state.

I see. Having global state is indeed a bit weird, but I would argue that if you use `default` for anything other than to satisfy the type checker, that's a programming error anyway. So if the returned value is weird, that'd be fine by me.

>I assume that you're asking this questions because you're trying to port aesop to the current Lean nightly, and you're having troubles with this GoalData structure.

Yes. More specifically `RappData`; `GoalData` can be `Inhabited` because of the `Option` there.

> My general advice would be to avoid circular references (parent?) and nested references.

This is how I did it in Lean 3. It's an okay solution, but it creates some additional overhead (not very much but still) and complicates the code a bit. And I feel like long term, I'm not going to be the only one who wants a data structure that isn't strictly tree-shaped.

**Comment by gebner** [comment]
> I would argue that if you use default for anything other than to satisfy the type checker, that's a programming error anyway.

This is certainly not true empirically, there are lots of uses of `default` in Lean core and even more in mathlib (looking at the largest code bases here).  The function is called `default` after all, encouraging its use as a default value.

Having an unsafe or surprising value easily available via a type class makes it almost certain it will be used accidentally (this is sometimes called a "footgun").

(That said, a default reference is only surprising but not unsafe.  The main reason FFI types like references lost their inhabited instances is because they were actually unsafe in general: the default was not a valid value for the type, causing crashes if you used it.)

> but it creates some additional overhead (not very much but still) and complicates the code a bit.

I'm willing to grant the extra indirection, though arenas are pretty popular for performance reasons (namely cache locality).

The code complication argument seems far fetched though.  You need a monadic operation to read the reference, looking up the index is no different.  If you define a `RappRef` wrapper and a `RappRef.get` function, then it's literally `← child.get` vs. `← child.get`.

If you absolutely insist on using references and refuse to use `Array.get`, then you can still manually define a `Inhabited (IO.Ref RappData)` instance (hope I got the type correct).

**Comment by leodemoura** [comment]
You can use the `initialize` command for showing that particular `IO.Ref a` types are inhabited.

```lean
def f (xs : Array (IO.Ref Nat)) : IO.Ref Nat :=
  xs[0] -- Error 

initialize refNat : IO.Ref Nat ← IO.mkRef 0

instance : Inhabited (IO.Ref Nat) where
  default := refNat

def g (xs : Array (IO.Ref Nat)) : IO.Ref Nat :=
  xs[0] -- Works
```

As @gebner pointed out, the change was intentional. Before https://github.com/leanprover/lean4/commit/e3241e82bce83048accbbb2eac3f281a7e74b5d7, the default `IO.Ref` instance would be an invalid value and a program would crash if it was used.

**Comment by JLimperg** [comment]
`initialize` is a nice workaround, thanks! Gabriel's and my design discussion probably doesn't belong here in the first place, so I'll leave it at that. ;)
